### ISSUE TITLE
Distrubute as an AppImage or as a debian file.

### ISSUE THREAD

**Issue by CasperOng** [UltimMC/Launcher#161]
### Role

I play cracked Minecraft.

### Suggestion

Distrubute as an AppImage or as a deb file. So that we can install it and launch it from the launcher instead of going to a folder and and right click run as a program.

### Benefit

uhh good for lazy peopple

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Distrubute as an AppImage or as a deb file. So that we can install it and launch it from the launcher instead of going to a folder and and right click run as a program.

**Comment by j3bx** [comment]
I just made a flatpak which kinda works, I just need to have the executable be able to choose another data folder, since the one the program itself uses has not write permissions

**Comment by Neptune650** [comment]
Done.

**Comment by Twig6943** [comment]
> I just made a flatpak which kinda works, I just need to have the executable be able to choose another data folder, since the one the program itself uses has not write permissions

Where's the repo for the said flatpak @j3bx
