### ISSUE TITLE
FTB Academy 1.16 and University 1.16 aren't working, they always crash, something to do with "minetogether"

### ISSUE THREAD

**Issue by GitEmulate** [UltimMC/Launcher#185]
### Operating System

Windows, Linux

### Description of bug

  Trying to run FTB Academy 1.16 always crashes and gives you this error screen
  ![crash](https://user-images.githubusercontent.com/102194165/164947872-7fe719bc-e893-4cda-a1fa-ef1afb35df4a.png)
   
  Here is the log 
[crash-2022-04-23_17.08.58-fml.txt](https://github.com/AfoninZ/UltimMC/files/8548707/crash-2022-04-23_17.08.58-fml.txt)

### Steps to reproduce

Download either of the mentioned packs through the in-built mod pack downloader from FTB, try to run them?

### Suspected cause

Vanilla 1.16 works fine. I tried a couple other 1.16 mod packs and they worked too. Academy 1.12 pack works (although on first boot it says this ![Screenshot from 2022-04-23 17-26-17](https://user-images.githubusercontent.com/102194165/164948023-73d5824c-d6a1-4158-ba25-e0286915f07f.png) but it works fine after that)

At first the Academy 1.16 pack didn't start at all, but it worked better when I switched from Java 11 to Java 8. However now it always goes to the previously shown error screen, "minetogether encountered an error". I tried just deleting minetogether's jar from the modpack but then I got a different crash (modpacks probably don't like you ripping out a mod that's supposed to be there :P)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by GitEmulate** [comment]
Addition: FTB Endeavor (1.16) and FTB OceanBlock (1.16) also don't work, same error screen "minetogether encountered an error" however "FTB Presents Direwolf20" pack (1.16) _does_ work.

**Comment by Samisafool** [comment]
It's because it's a cracked launcher. Not related to UltimMC

**Comment by GitEmulate** [comment]
> It's because it's a cracked launcher. Not related to UltimMC

Yeah I figured that. But what should I do then? Can I just, not play any of the modpacks with Minetogether? Is there atleast a workaround, some way to remove it from the modpack without the modpack just crashing?

**Comment by Samisafool** [comment]
Main screen > Click on pack > Edit Instance > Mods

find minetogether and delete

**Comment by GitEmulate** [comment]
> Main screen > Click on pack > Edit Instance > Mods
> 
> find minetogether and delete

I tried that already, this is what happens
![crashy](https://user-images.githubusercontent.com/102194165/164957360-2992afdf-36c9-4a81-a050-f16d13e39c26.png)

[crash-2022-04-23_23.57.27-client.txt](https://github.com/AfoninZ/UltimMC/files/8549050/crash-2022-04-23_23.57.27-client.txt)

**Comment by Samisafool** [comment]
Some mods might need java 16, try using that

**Comment by GitEmulate** [comment]
> Some mods might need java 16, try using that

Tried using Java 16, same result, "The following mod(s) have been identified as potential causes: No Mods". Java 17 just causes it to crash before it even starts.

**Comment by andreefl** [comment]
What's in the generated log file?

**Comment by GitEmulate** [comment]
> What's in the generated log file?

I uploaded the logs above

**Comment by RobertoVGoulart** [comment]
Same problem here.

**Comment by yum13241** [comment]
Workaround, switch to Fabric and use https://essential.gg/en/, at least for now.


Hell, there are even installers and forge versions lol
