### ISSUE TITLE
libQt5Xml.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by username100099** [UltimMC/Launcher#213]
### Operating System

Linux

### Description of bug

when opening the file on linux it says /home/myusername/Downloads/mmc-cracked-lin64/UltimMC/UltimMC: error while loading shared libraries: libQt5Xml.so.5: cannot open shared object file: No such file or directory

### Steps to reproduce

install it using the default steps.

### Suspected cause

qt5 missing.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Samisafool** [comment]
Distro?

**Comment by username100099** [comment]
ChromeOS/linux

**Comment by Samisafool** [comment]
You will have to figure out how to get Qt on chromeos then.

**Comment by username100099** [comment]
oh ok thanks! i just ran apt install libQt5Xml and it worked.
