### ISSUE TITLE
When using forge the game crashes instead of it opening.

### ISSUE THREAD

**Issue by ANDREI12333** [UltimMC/Launcher#214]
### Operating System

Windows

### Description of bug

When using forge the game crashes instead of it opening.

### Steps to reproduce

* Open the launcher
* Create a new instance
* Install forge on that specific instance
* Launch the instance.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ka1dz0** [comment]
The problem is on your side, everything runs fine
![xyrGz8996NE](https://user-images.githubusercontent.com/98089031/174392088-334fff2b-0795-47b4-a7e8-387bb455e9c1.png)
