### ISSUE TITLE
Use PolyMC as upstream fork

### ISSUE THREAD

**Issue by Cynosphere** [UltimMC/Launcher#215]
PolyMC has features that MultiMC won't ever (get around to) implementing, let alone fixing issues like #199 and #207.

Relying on an upstream maintained by ignorant and toxic maintainers that are willing to bend to the will of corporations opposed to the users isn't the solution.

**Comment by iamtakingithard** [comment]
Hello, I just made forks of these repos.

If you are Windows, Mac, Linux user, then please follow this [link](https://github.com/iamtakingithard/PolyMC-with-patches)
If you are Mac M1 user, then please follow [here](https://github.com/iamtakingithard/ManyMC-with-patches) 

Have fun!

**Comment by Samisafool** [comment]
Doesn't seem to be UltimMC patches?

**Comment by iamtakingithard** [comment]
> Doesn't seem to be UltimMC patches?

Yes. Since both ManyMC and PolyMC have offline mode included, all I did is just got rid of requirement to get an account.

**Comment by Samisafool** [comment]
It doesn't have ElyBy auth, etc... A downgrade from UltimMC, right?

**Comment by iamtakingithard** [comment]
> It doesn't have ElyBy auth, etc... A downgrade from UltimMC, right?

Yes, it doesn't. As I said I don't really need ElyBy auth, works fine for me. In general it doesn't use authlib-injector method.

**Comment by iamtakingithard** [comment]
> Yes but many people want skins. Not asking you to implement, just saying

I **may try** to do that, but I would like to keep up with upstream without any issues/major changes in code.

**Comment by iamtakingithard** [comment]
> Moving to an issue in ur repo
> 
> Edit: can you enable those?

I can try, but I am not guarantee anything. The issue with trying to apply UltimMC patches, is that there was tons of commits for authlib, then dehardcode of account providers etc.

> Moving to an issue in ur repo
> 
> Edit: can you enable those?

**Comment by Neptune650** [comment]
While I initially agreed with your suggestion, recently there has been controversy regarding PolyMC, if you wish to propose a better alternative, feel free to do so.

**Comment by MenacingPerson** [comment]
Prism Launcher.

**Comment by Cynosphere** [comment]
Yeah this issue was made before the PolyMC controversy
