### ISSUE TITLE
add curseforge and FTB again like ATLauncher or PolyMC

### ISSUE THREAD

**Issue by son123cats** [UltimMC/Launcher#222]
### Role

play modded minecraft.

### Suggestion

Add again like 2 launcher, when we install a curseforge modpack, we just need to download some mod on the link launcher suggest

### Benefit

me and other can play more modpack

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

sorry about my english, because i'm Vietnamese

![Capture](https://user-images.githubusercontent.com/82934378/179190870-c77ca728-087e-46fe-a06c-c5cafae4cd42.PNG)
![Capture1](https://user-images.githubusercontent.com/82934378/179190875-8305322c-1d6b-416c-9c26-1574ac2e72fc.PNG)
![Capture2](https://user-images.githubusercontent.com/82934378/179190882-5ad22e14-0d53-4e18-97e3-697503a8d308.PNG)
![Capture4](https://user-images.githubusercontent.com/82934378/179190885-7e35a553-c685-4274-b232-688b316bedae.PNG)

**Comment by Neptune650** [comment]
Our intention is to stay as close to the original MultiMC as possible, please alternatively use Prism Launcher and such when you desire these features, or, request they get upstreamed to MultiMC.
