### ISSUE TITLE
Can't add local account - related to proxy?

### ISSUE THREAD

**Issue by treysis** [UltimMC/Launcher#224]
### Description of bug

When I try to add a local account, I get the following error:

```Mojang user authentication ended with a network error.```

### Steps to reproduce

Launch UltimMC -> Settings -> Accounts -> Add Account -> enter whatever, select Local -> click Ok

### Suspected cause

I suspect this could be because I have to use a HTTP proxy (supports CONNECT method for HTTPS connections). I have entered the proxy details in the settings. The proxy only allows connections to few ports (22, 80, 443 afaik). Could it be that UltimMC tries to connect without using the proxy?

I can download the resources and everything just fine. Just adding the account doesn't work. Why does UltimMC need to connect anyways if I am using a Local account anyways?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by stutsanks** [comment]
Well i have the issue opposite of you. i can get a offline account there but the libraries i cant install due to my ssl certificate expired. For your issue, try the second option. it might work

**Comment by treysis** [comment]
You mean "ely.by"? That one also doesn't seem to work with proxies. It tries to resolve the host locally, but name resolution has to work through proxy.

I was now able to add a local account. I first had to disable proxy in the settings. It seems to add a local account a connection has to be made to `localhost`. But if a proxy is set up, it tries to connect to `localhost` through the proxy. Obviously, this can't work.

So, for adding a local account, proxy should not be used.

**Comment by Neptune650** [comment]
Local accounts no longer connect to any domain at all, fixed.
