### ISSUE TITLE
The password field still shows when making a local account

### ISSUE THREAD

**Issue by ghost** [UltimMC/Launcher#228]
### Operating System

Windows, macOS, Linux, Other

### Description of bug

Having the local account creation selected when adding an account still shows the password button

### Steps to reproduce

Go to settings > accounts

Press add account

The local account option has a passwork field which makes no sence there

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ka1dz0** [comment]
**Why ask such stupid questions????
Write something random in the password field - any letter or number....**
_Check first, and then write stupid questions_

**Comment by Cyimil** [comment]
Fill it with anything

**Comment by ghost** [comment]
> **Why ask such stupid questions???? Write something random in the password field - any letter or number....** _Check first, and then write stupid questions_



> Fill it with anything

I'm not saying i don't know I can fill it with anything, it's that the field absolutely useless there and only causes confusion.

**Comment by ghost** [comment]
@Cyimil please elaborate. I know I can fill it with anything, it just makes no sence that the field is even there. It should be removed whatsoever.

**Comment by Neptune650** [comment]
Fixed.
