### ISSUE TITLE
Unable to apply skin. 

### ISSUE THREAD

**Issue by Agent24xx** [UltimMC/Launcher#230]
![Screenshot (2)](https://user-images.githubusercontent.com/110902322/185411222-759ac8b4-7885-4961-b0d4-9051dada8737.png)
I have a skin file in .png .when i try to upload it to my local account it says failed to upload. How do I fix it?

**Comment by avg-jung-enjoyer** [comment]
Same issue here, I believe it has something to do with skin uploads requiring authentication:

- 3156.443 D Task "SkinUpload(0x12e87330)" starting for the first time

- 3156.569 C Network error: QNetworkReply::NetworkError(AuthenticationRequiredError)

- 3156.569 C Task "SkinUpload(0x12e87330)" failed:  "Host requires authentication"

- 3156.569 C Task "SequentialTask(0xc04b04)" failed:  "Host requires authentication"

- 3156.573 C Task "SkinUpload(0x12e87330)" failed while not running!!!!:  "Network error: Host requires authentication"

**Comment by GTHB-plyr7510** [comment]
Come on devs, It's been a year since this issue was published. Can't you just help us out?

**Comment by Figarist** [comment]
Any updates?

**Comment by Figarist** [comment]
up

**Comment by Neptune650** [comment]
Fixed (by disabling the buttons, since ely.by doesn't provide an API to change skins, just use their web UI)
