### ISSUE TITLE
UltimMC "can't be opened" issue on M1 Mac

### ISSUE THREAD

**Issue by k414r** [UltimMC/Launcher#231]
### Operating System

M1 Mac

### Description of bug

Hi, 

Whenever I try to open the app, I am receiving this error message. I am not sure what to do and I've tried to do whatever was suggested on the install guide, but nothing seems to work.

### Steps to reproduce

Try to open the app, and I instantly receive the error message.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by MenacingPerson** [comment]
Which error? Also UltimMC won't work on M1.
