### ISSUE TITLE
Issue with JDK on M1 Mac, showing 32 bit instead of 64

### ISSUE THREAD

**Issue by k414r** [UltimMC/Launcher#232]
### Operating System

macOS

### Description of bug

Hi, 

I downloaded the correct JDK to use for the launcher, which is 18.0.2.
However, when I select edit instance and try to use this, it is displaying as '32 bit', even though I downloaded the arm64 dmg. I tried using ManyMC, and even that displayed that this is the correct architecture to use. Is UltimMC misidentifying the 64 bit file? Or is there some other problem? Should I use a different jdk?

<img width="783" alt="Screen Shot 2022-08-16 at 12 16 08 PM" src="https://user-images.githubusercontent.com/111337887/184814864-dc0d9b31-8ea7-403f-a924-3e168d2838b9.png">
'

### Steps to reproduce

Select edit instance
Navigate to Java panel of Settings
Press 'Auto Detect'
Only showing 32 bit.

### Suspected cause

System may be misidentifying the jdk.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
UltimMC doesn't touch anything related to the JDK, and UltimMC doesn't provide any builds for M1, this is not an UltimMC problem.
