### ISSUE TITLE
Can't join servers

### ISSUE THREAD

**Issue by iRegretEverything** [UltimMC/Launcher#233]
### Operating System

Windows

### Description of bug

When I join a server, I get an error saying "Bad packet id 26", the server is set to offline mode.
I tried using local, ely,by account. Both give this error.

![Screenshot (6)](https://user-images.githubusercontent.com/111980026/186407713-01cd0f00-45d9-4c2e-8754-7690ae235c3e.png)

### Steps to reproduce

* Launch Minecraft (Happens to me in 1.14.2)
* Join any Multiplayer Server
* You would get an error

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ThanZaf** [comment]
Same problem here

**Comment by Marcelo20XX** [comment]
The host of the server must allow "cracked" clients or launchers... some come with this feature while others disable the connection from those clients...
