### ISSUE TITLE
Cannot run the latest version on Mac OS X 10.13.6

### ISSUE THREAD

**Issue by giabao06** [UltimMC/Launcher#234]
### Operating System

macOS

### Description of bug

UltimMC crashes on startup on Mac OS X 10.13.6.

### Steps to reproduce

1. Download and extract the latest mmc-cracked-osx64.zip
2. Extract the .app file
3. `chmod +x` the .app file as well as the ./UltimMC file in `UltimMC.app/Contents/MacOS/UltimMC` 
4. Run the .app file

### Suspected cause

Might be a library built for Mac OS 11? Beginning of crash report below:

```
Process:               UltimMC [1396]
Path:                  /Users/USER/Desktop/UltimMC.app/Contents/MacOS/UltimMC
Identifier:            org.multimc.UltimMC
Version:               0.7.0.-1 (0.7.0.-1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           UltimMC [1396]
User ID:               501

Date/Time:             2022-09-01 21:18:09.722 +0700
OS Version:            Mac OS X 10.13.6 (17G14042)
Report Version:        12
Anonymous UUID:        (removed)


Time Awake Since Boot: 9500 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Application Specific Information:
dyld: in dlopen()
libresolv.so

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Users/USER/Desktop/UltimMC.app/Contents/MacOS/../MacOS/libpcre2-16.0.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
  
  ```
  

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by sadlermeetscode** [comment]
Hey @giabao06,

I was having this same issue on Ventura. Found out a fix that worked for me and may solve the issue. 

It seems like the built-in MacOS Archive Utility was breaking the app when unzipping it. 

I fixed mine by using another unarchiving app called The Unarchiver. Let me know if this helps.

**Comment by Neptune650** [comment]
In theory shouldn't happen with the latest build, please reopen if it still happens.

**Comment by khuongtp** [comment]
I'm on macos 14.2.1 and it doesn't work at all, same Exception Type as above, when I tried to compile the code myself, I got an error saying that index is defined but not used in the translation.cpp file (I can't remember exactly the path)
Edit: macbook pro m1 max
