### ISSUE TITLE
UltimMC remnants - not bug report, question

### ISSUE THREAD

**Issue by CodeGenStudio** [UltimMC/Launcher#235]
### Operating System

Windows

### Description of bug

Note: THIS IS NOT A BUG (this is a question)

So basically if I install UltimMC on my Windows 10 64-bit machine, where does UltimMC create files? Does it do anything in Program files, appdata, etc etc and does it make an registry entries? I want to know because if I uninstall UltimMC I want to complete remove it without a trace. I haven't downloaded the prebuilt-binary yet, I first wanted to ask this.

Thanks

### Steps to reproduce

-

### Suspected cause

-

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by MenacingPerson** [comment]
You extract it to a folder, and it stays confined to it. No other places it creates anything.

**Comment by CodeGenStudio** [comment]
> You extract it to a folder, and it stays confined to it. No other places it creates anything.

Oh ok, thanks a lot
