### ISSUE TITLE
"Failed to upload skin!"

### ISSUE THREAD

**Issue by sutacselif** [UltimMC/Launcher#236]
### Operating System

_Windows_

### Description of bug

tried to upload a skin then i got the popup: "Failed to upload skin!" 

### Steps to reproduce

- Run UltimMC
- Click on the Profiles Tab on the top right
- Click on Manage Accounts
- Select an account
- Click Upload Skin
- Choose Skin File
- Click OK

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by severtheskyline** [comment]
Not sure why this is closed, because when you are using a local account, it says error when trying to use a skin.
