### ISSUE TITLE
Nightly link doesn't work

### ISSUE THREAD

**Issue by cdparanoia** [UltimMC/Launcher#238]
### Role

I suggest this launcher

### Suggestion

Fix nightly link

### Benefit

People can play minecraft without Microsoft bloat

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by MenacingPerson** [comment]
https://nightly.link/UltimMC/Launcher/workflows/main/develop

here is the one that works, @Sebastian-byte please fix
