### ISSUE TITLE
when trying to extract the MMC Cracked zip file, it shows as corrupted

### ISSUE THREAD

**Issue by ghost** [UltimMC/Launcher#239]
### Operating System

Windows

### Description of bug

It happens in Opera and Chrome and Winrar and 7Zip.
I have tried disabling the antivirus, and tried on another computer. It still doesn't work. Does it have to do with the file or my computer?

### Steps to reproduce

![188341997-8ca7d90a-818e-4d9e-9538-12cfae797940](https://user-images.githubusercontent.com/112835028/188342279-dc3fa598-0a06-4ad2-8293-6ed63dec9a7b.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
This is a common GitHub Actions problem, please wait and redownload.
