### ISSUE TITLE
UltimMC communicates with ```api.minecraftservices.com``` when adding local accounts/ launching an instance in offline mode

### ISSUE THREAD

**Issue by WRF5riNr** [UltimMC/Launcher#240]
### Operating System

Linux

#### Main issue

When creating a local account, or launching an instance in offline mode, UltimMC communicates with ```api.minecraftservices.com``` (as seen when using [OpenSnitch](https://github.com/evilsocket/opensnitch) application firewall).

![Screenshot from 2022-09-06 08-37-03_edit](https://user-images.githubusercontent.com/112424003/188524254-6cf4acf7-4e21-45f1-bc3a-07bd726cfb7a.png)

#### Behaviour with internet connection

Launching an instance in offline mode:

![Screenshot from 2022-09-06 08-09-55](https://user-images.githubusercontent.com/112424003/188524975-b17a4db3-387f-4c20-a435-6ef8de6d4a22.png)
![Screenshot from 2022-09-06 08-10-05](https://user-images.githubusercontent.com/112424003/188525014-a49565bb-5cb0-449a-b4d7-4e45e265be54.png)
![Screenshot from 2022-09-06 08-10-15](https://user-images.githubusercontent.com/112424003/188525056-ddb9a928-3702-4b43-bcb6-8571b50a4ec1.png)

Creating a local account:

![Screenshot from 2022-09-06 08-17-34](https://user-images.githubusercontent.com/112424003/188525140-0c8ac03b-f6c5-4905-8ba2-f584963feeee.png)
![Screenshot from 2022-09-06 08-17-38](https://user-images.githubusercontent.com/112424003/188525147-b81df6ea-3df0-4b9f-b49e-8b283caf0236.png)
![Screenshot from 2022-09-06 08-17-47](https://user-images.githubusercontent.com/112424003/188525159-a3e5d3da-8f34-48fc-a33a-058d66abdffd.png)

UltimMC communicates with ```api.minecraftservices.com``` during this sequence, which in total takes less than a second.

#### Behaviour without internet connection

UltimMC tries to communicate with ```api.minecraftservices.com```, though the above sequence is not shown and it proceeds immediately.

#### Behaviour with/ without an internet connection, but with OpenSnitch set to block ```api.minecraftservices.com```

UltimMC tries to communicate with ```api.minecraftservices.com``` and the above sequence is shown. However, each step in the sequence takes 10 seconds to complete (or to supposedly time out). Hence in total, it takes 30 seconds when creating a local account, or launching an instance in offline mode. 

#### Behaviour when ```api.minecraftservices.com``` is not reachable or blocked on network level

Not tested, but I believe it will have the same result as the OpenSnitch scenario.

### Steps to reproduce

- Use OpenSnitch or any network inspection tool.
- (Optional) block ```api.minecraftservices.com``` using OpenSnitch.
- Create a local account, or launch an instance in offline mode in UltimMC.

### Reasons for creating issue

- It is probably not necessary to communicate with ```api.minecraftservices.com``` whenever creating a new local account or launching in offline mode. 
- UltimMC will work faster in scenarios where ```api.minecraftservices.com``` is not reachable, blocked on network level, or by application firewall. 
- Microsoft/ Mojang does not need to be notified of offline usage of UltimMC (user privacy).

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
Fixed.
