### ISSUE TITLE
Make a new release/tag

### ISSUE THREAD

**Issue by Kreyren** [UltimMC/Launcher#242]
I am trying to package this, but the last tag was in 2020 -> plz stage a new one thanku

**Comment by psynyde** [comment]
+1

**Comment by xknat** [comment]
you should use the **Pre-built binaries** see https://github.com/UltimMC/Launcher/blob/develop/README.md#pre-built-binaries

**Comment by Kreyren** [comment]
> you should use the Pre-built binaries see https://github.com/UltimMC/Launcher/blob/develop/README.md#pre-built-binaries @xknat (https://github.com/UltimMC/Launcher/issues/242#issuecomment-1277218175)

We don't do pre-built binaries on GNU Guix.

**Comment by MenacingPerson** [comment]
> GNU Guix

In that case can I suggest packaging "Pollymc" (sic)? MultiMC, while being open source, is not open source friendly.

https://github.com/fn2006/PollyMC

**Comment by Kreyren** [comment]
How is that more open-source friendly?

------- Original Message -------

**Comment by MenacingPerson** [comment]
https://polymc.org/news/moving-on/

Some context

**Comment by Neptune650** [comment]
Done.
