### ISSUE TITLE
How to implement your authlib setting to my launcher fork?

### ISSUE THREAD

**Issue by catfromplan9** [UltimMC/Launcher#244]
Hello, I maintain my own fork of multimc for a few friends and i patched it to use my selfhosted auth server, but how can i automatically add the default java options for -javaagent:/path/authlib-injector-1.2.1.jar=server.com as your ultimmc does? thanks in advance

**Comment by catfromplan9** [comment]
and, of course, how can i get authlib injector downloaded automatically as yours does?

**Comment by mlkpnck** [comment]
> and, of course, how can i get authlib injector downloaded automatically as yours does?

[how did you solve this issue](https://translate.yandex.ru/)

**Comment by catfromplan9** [comment]
> > and, of course, how can i get authlib injector downloaded automatically as yours does?
> 
> [how did you solve this issue](https://translate.yandex.ru/)

I use fjord launcher now, it provides the necessary functionality
