### ISSUE TITLE
Internal exception: java.io.IOException: The received string length longer than maximum (36>16)

### ISSUE THREAD

**Issue by Trampa3** [UltimMC/Launcher#247]
### Operating System

Windows

### Description of bug

Internal exception: java.io.IOException: The received string length longer than maximum (36>16)

Not take more info only to servers Readme other names to new player????

### Steps to reproduce

https://pastes.dev/SI92C4MXko
https://pastes.dev/p5mKSCSy6k

https://paste.shockbyte.com/dohoyohakajiwacusare

Log to my consoles Server

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Wiener234** [comment]
Try making your Ingame Name shorter

**Comment by Neptune650** [comment]
The pastes have been removed, also do consider making your username more short.
