### ISSUE TITLE
Download All button enforcing Mojang account

### ISSUE THREAD

**Issue by zshzebra** [UltimMC/Launcher#248]
### Operating System

Linux

### Description of bug

When you click the download all button on the version tab in an instance's properties, when you click the button, it tries to force you to use a Mojang account, but launching the instance works fine

### Steps to reproduce

Click edit instance on an instance, then click version  then download all (make sure no Mojang account present)

### Suspected cause

No patched the download all button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by shoo-p** [comment]
click on manage accounts, and refresh your local account to change it to working

**Comment by Neptune650** [comment]
Fixed now.
