### ISSUE TITLE
The application “UltimMC” can’t be opened on macOS Ventura

### ISSUE THREAD

**Issue by evanonym0us** [UltimMC/Launcher#250]
![Screenshot 2022-11-21 at 10 41 48 AM](https://user-images.githubusercontent.com/44841254/203096708-019d774b-0c10-45e8-b078-2812bbaef79a.png)

I am unable to open the application on my Macbook running Ventura.

**Comment by CasperOng** [comment]
Try to type this in terminal:

chmod +x UltimMC.app/Contents/MacOS/UltimMC

**Comment by CasperOng** [comment]
And 
`chmod +x ~/Applications/UltimMC`

**Comment by evanonym0us** [comment]
That worked, thank you :)
