### ISSUE TITLE
Can't change skin

### ISSUE THREAD

**Issue by pmagixc** [UltimMC/Launcher#251]
### Operating System

Linux

### Description of bug

Can't change the skin, tried with ely.by account and a local account

`  137.212 C Network error:  QNetworkReply::AuthenticationRequiredError
  137.213 C Task "SkinUpload(0x56185c20a610)" failed:  "Host requires authentication"
  137.213 C Task "SequentialTask(0x7ffca41c45a0)" failed:  "Host requires authentication"
  137.214 C Task "SkinUpload(0x56185c20a610)" failed while not running!!!!:  "Network error: Host requires authentication"
  139.745 C Network error:  QNetworkReply::AuthenticationRequiredError
  139.746 C Task "SkinDelete(0x56185c3e13f0)" failed:  "Host requires authentication"
  139.747 C Task "SkinDelete(0x56185c3e13f0)" failed while not running!!!!:  "Network error: Host requires authentication"
  147.425 W AuthRequest::onRequestError: Error 204
  147.425 W AuthRequest::onRequestError: Error string:  "Host requires authentication"
  147.425 W AuthRequest::onRequestError: HTTP status 401 "Unauthorized"
  147.629 W AuthRequest::onRequestError: Error 204
  147.629 W AuthRequest::onRequestError: Error string:  "Host requires authentication"
  147.629 W AuthRequest::onRequestError: HTTP status 401 "Unauthorized"
  147.834 W AuthRequest::onRequestError: Error 204
  147.834 W AuthRequest::onRequestError: Error string:  "Host requires authentication"
  147.834 W AuthRequest::onRequestError: HTTP status 401 "Unauthorized"
  147.834 W AuthRequest::onRequestError: Error 301
  147.834 W AuthRequest::onRequestError: Error string:  "Protocol \"\" is unknown"
  147.834 W AuthRequest::onRequestError: HTTP status 0 ""
`

### Steps to reproduce

Create/connect any account and try to change the skin.

### Suspected cause

The launcher tries to authenticate with some mojang server of some sort I think, but I can be wrong.

`
  137.212 C Network error:  QNetworkReply::AuthenticationRequiredError
  137.213 C Task "SkinUpload(0x56185c20a610)" failed:  "Host requires authentication"
  137.213 C Task "SequentialTask(0x7ffca41c45a0)" failed:  "Host requires authentication"
  137.214 C Task "SkinUpload(0x56185c20a610)" failed while not running!!!!:  "Network error: Host requires authentication"
  139.745 C Network error:  QNetworkReply::AuthenticationRequiredError
  139.746 C Task "SkinDelete(0x56185c3e13f0)" failed:  "Host requires authentication"
  139.747 C Task "SkinDelete(0x56185c3e13f0)" failed while not running!!!!:  "Network error: Host requires authentication"
  147.425 W AuthRequest::onRequestError: Error 204
  147.425 W AuthRequest::onRequestError: Error string:  "Host requires authentication"
  147.425 W AuthRequest::onRequestError: HTTP status 401 "Unauthorized"
  147.629 W AuthRequest::onRequestError: Error 204
  147.629 W AuthRequest::onRequestError: Error string:  "Host requires authentication"
  147.629 W AuthRequest::onRequestError: HTTP status 401 "Unauthorized"
  147.834 W AuthRequest::onRequestError: Error 204
  147.834 W AuthRequest::onRequestError: Error string:  "Host requires authentication"
  147.834 W AuthRequest::onRequestError: HTTP status 401 "Unauthorized"
  147.834 W AuthRequest::onRequestError: Error 301
  147.834 W AuthRequest::onRequestError: Error string:  "Protocol \"\" is unknown"
  147.834 W AuthRequest::onRequestError: HTTP status 0 ""
`

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by pmagixc** [comment]
literally no support ongo ongongo ong

**Comment by Choommi** [comment]
Yeah i can't change my skin too it says failed to upload skin and ely by just gives out my email in game

**Comment by mailmanjoe** [comment]
you dont really have to give your email just type in what ever you want

**Comment by Neptune650** [comment]
Fixed (by disabling the buttons, since ely.by doesn't provide an API to change skins, just use their web UI)

**Comment by KhiemGOM** [comment]
> Fixed (by disabling the buttons, since ely.by doesn't provide an API to change skins, just use their web UI)

@Neptune650 So to resolve this I have to have an ely.by skin? No way to change skin for Offline acc?
