### ISSUE TITLE
There isn't a Win 64x download?

### ISSUE THREAD

**Issue by WahYeah1** [UltimMC/Launcher#254]
### Description of bug

THIS IS NOT A BUG. 

There isn't a Windows 64 bit version. 

### Steps to reproduce

*

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by thebashforkbomber** [comment]
there is you goomba stomper
the regular download itself is x64, the other one is x32 just for the compactability

**Comment by Neptune650** [comment]
Download the x86/x32 version, should work just fine.
