### ISSUE TITLE
List update failed

### ISSUE THREAD

**Issue by someGermandUdE** [UltimMC/Launcher#257]
### Operating System

Windows

### Description of bug

When i click on New instance or klicking on Refresh in New Instance it shows the error: List update failed:
Job 'Download of meta file net.minecraft/index.json' failed to process:
https://meta.multimc.org/v1/net.minecraft/index.json

instead if showing me minecraft versions i could download.

### Steps to reproduce

1. open ultimMC
2. click on "Add Instance"
3. If the Error doesnt pop up, click on Refresh

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by BabyBoy666** [comment]
same issue

**Comment by Neptune650** [comment]
Unable to reproduce, could've been just a temporal bug with the meta server?
