### ISSUE TITLE
Can't open on MacOS 10.14

### ISSUE THREAD

**Issue by giacomocaironi** [UltimMC/Launcher#258]
### Operating System

macOS

### Description of bug

When i try to run it I get the following error
```
dyld: Library not loaded: @executable_path/../MacOS/libpcre2-16.0.dylib
  Referenced from: /Users/marco/Downloads/UltimMC.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
  Reason: no suitable image found.  Did find:
        /Users/marco/Downloads/./UltimMC.app/Contents/MacOS/../MacOS/libpcre2-16.0.dylib: cannot load 'libpcre2-16.0.dylib' (load command 0x80000034 is unknown)
        /Users/marco/Downloads/./UltimMC.app/Contents/MacOS/../MacOS/libpcre2-16.0.dylib: stat() failed with errno=1
        /Users/marco/Downloads/UltimMC.app/Contents/MacOS/../MacOS/libpcre2-16.0.dylib: cannot load 'libpcre2-16.0.dylib' (load command 0x80000034 is unknown)
        /Users/marco/Downloads/UltimMC.app/Contents/MacOS/../MacOS/libpcre2-16.0.dylib: stat() failed with errno=1
Abort trap: 6
```

### Steps to reproduce

Follow the instructions in the readme end then execute the application using MacOS 14

### Suspected cause

Maybe a difference between my pc and the environment where the application is compiled?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by MecBonjourno** [comment]
Same here

**Comment by binarctq** [comment]
Same issue, 10.14.6 with Qt5 installed from macports version 5.15.8_0

I can launch the original MultiMC just fine without any errors on the same machine.

Did find a [similar issue](https://www.cloudynights.com/topic/845593-starnet-help-on-macos-10131/) (with another library) that suggested the load command specified in the error, `LC_DYLD_CHAINED_FIXUPS`, is too new for macOS 10.14?

I do not have a newer macOS version to test on, so maybe others can test this out on newer versions.

**Comment by Neptune650** [comment]
In theory shouldn't happen with the latest build, please reopen if it still happens.
