### ISSUE TITLE
Shaders possible? Unable to see shaders tab with what I've tried so far

### ISSUE THREAD

**Issue by aaroncorbin** [UltimMC/Launcher#259]
I've installed Iris and my shaderpack, added them to mods and shader packs tabs respectively, made sure that they are installed under the instances folder. Is there something I'm missing or is it just not possible?

**Comment by yum13241** [comment]
The shaders tab is a Pol**l**yMC feature afaik. Note the double L.

**Comment by Neptune650** [comment]
We don't offer this feature [yet].
