### ISSUE TITLE
mmc-cracked-win32-5152

### ISSUE THREAD

**Issue by QueenUlyana** [UltimMC/Launcher#261]
### Role

Explanation

### Suggestion

Write the difference between mmc-cracked-win32 and mmc-cracked-win32-5152. PLEASE!!!

### Benefit

Information

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Neptune650** [comment]
mmc-cracked-win32-5152 uses Qt 5.15, which is not stable yet and you should use the normal build.
