### ISSUE TITLE
Worlds dissapearing and reappearing

### ISSUE THREAD

**Issue by irokes360** [UltimMC/Launcher#262]
### Operating System

Windows

### Description of bug

I started playing minecraft on UltimMC 2 days ago, and created a world.  Yesterday, the world dissapeared, so I had to create a new one. But today, the world from yesterday dissapeared, and the world from 2 days ago reappeared. (the world from 2 days ago wasn't in the save folder, i checked). Why is that happening?

### Steps to reproduce

* I don't even know what could be causing that, the world dissapeared from saves file and then magically reappeared

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
Not related to the launcher (possible hardware failure?)
