### ISSUE TITLE
MCEdit doesn't see the minecraft versions folder

### ISSUE THREAD

**Issue by philbibliography** [UltimMC/Launcher#263]
### Operating System

Windows

### Description of bug

If I try to open a world with MCEdit, the app doesn't detect the minecraft versions folder

### Steps to reproduce

Just open a world with MCEdit

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
Not related to UltimMC itself, closing.
