### ISSUE TITLE
Use Prism Launcher as base

### ISSUE THREAD

**Issue by ghost** [UltimMC/Launcher#264]
### Role

Modding

### Suggestion

Use Prism Launcher as base

### Benefit

It will have way more feature than this one, including curseforge support

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by floorshame** [comment]
💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀
