### ISSUE TITLE
gets stuck on downloading assets file on mojang

### ISSUE THREAD

**Issue by unnaturalistic** [UltimMC/Launcher#265]
### Description of bug

cannot add new version

### Steps to reproduce

click instances
choose version
new instance

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by BabyBoy666** [comment]
already posted: https://github.com/UltimMC/Launcher/issues/257#issue-1523069955

**Comment by Neptune650** [comment]
Duplicate of #257
