### ISSUE TITLE
Launch offline not working

### ISSUE THREAD

**Issue by Niotferdi** [UltimMC/Launcher#267]
### Description of bug

I want to play minecraft without internet. But when I press the "Launch Offline" button in UltimMC, I get an infinite loading bar "Logging in with Mojang account." My launcher account is of type local. Before that, I had a Mojang license, but I lost it during the migration (I don’t like MS accounts).

### Steps to reproduce

Run any instance in ultimmc without internet (turn off Wi-Fi or block in firewall)

### Suspected cause

The "local" account in the launcher is not local enough.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Niotferdi** [comment]
I will add. For those 5 minutes while I was writing the issue, the scale "Logging in with Mojang account." disappeared, and I was able to click on the offline start button, which now works. But waiting for a few minutes before the game just like that is humiliating.

**Comment by thebashforkbomber** [comment]
Thats because the launcher IS AUTOMATICALLY LAUNCHES IN OFFLINE MODE

**Comment by Neptune650** [comment]
Should work fine now.
