### ISSUE TITLE
crashing with a single mod, error 255 (0xff)

### ISSUE THREAD

**Issue by idksomeone0** [UltimMC/Launcher#268]
### Operating System

Ubuntu

### Description of bug

I expected the game to launch, it didn't with an exit code of 255, and it's incorrect because the game closed right when a bit of the loading bar got filled (about half a second after the window pops up)

log:
[e.txt](https://github.com/UltimMC/Launcher/files/11012965/e.txt)

### Steps to reproduce

enable the mod (forge 43.2.0
launch
windows appears
a small bit of the bar gets filled
window closes abruptly

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by idksomeone0** [comment]
how do I check if the mod is just broken somehow

**Comment by masuyamadaiki** [comment]
how to get mod

**Comment by Neptune650** [comment]
Unlikely to be related to UltimMC itself, closing.
