### ISSUE TITLE
Still prompts for mojang and microsoft

### ISSUE THREAD

**Issue by Faceless1267** [UltimMC/Launcher#270]
### Description of bug

Title. After being downloaded the launcher still asks for an account sign in

### Steps to reproduce

![image](https://user-images.githubusercontent.com/131113210/232661010-e89d8ff2-72ae-40cd-938b-a7aa0fd38473.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by thebashforkbomber** [comment]
The text was just unedited lmao
Go create a cracked account with this infO:
Press yes (or just go to the account manager by pressing the steve head or "Profile" at the upper right)
Press Add Account in the account manager and for the email you write your wanted nickname
Then password should be whatever you want

**Comment by thebashforkbomber** [comment]
> The text was just unedited lmao Go create a cracked account with this infO: Press yes (or just go to the account manager by pressing the steve head or "Profile" at the upper right) Press Add Account in the account manager and for the email you write your wanted nickname Then password should be whatever you want

also what system did you use i dont' understand a fuck

**Comment by Neptune650** [comment]
Use the add account feature and pick local as an option, pick an username and then add whatever you'd like as password
