### ISSUE TITLE
not found

### ISSUE THREAD

**Issue by EF4WCVB3** [UltimMC/Launcher#272]
### Description of bug

it says not 'the code execution cannot proceed because liblauncher_iconfix.dll was not found. reinstalling the program may fix this problem also lib launcher_nbt+++.dll not found

### Steps to reproduce

it says not 'the code execution cannot proceed because liblauncher_iconfix.dll was not found. reinstalling the program may fix this problem also lib launcher_nbt+++.dll not found

### Suspected cause

idk know what is issuse tracker

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
Your download is corrupted.
