### ISSUE TITLE
Raspberry pi?

### ISSUE THREAD

**Issue by cdkw2** [UltimMC/Launcher#273]
### Role

I want to play on a raspberry pi. 

### Suggestion

Make a raspberry pi version. 

### Benefit

To reach a larger audience. 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Raspberry pi support please! I am ready to play test your builds if you want.

**Comment by tobycm** [comment]
try build the project on your pi, it may take a while but you could try

**Comment by Neptune650** [comment]
Upstream doesn't have RPI support.
