### ISSUE TITLE
Launcher not even opening on Linux

### ISSUE THREAD

**Issue by Throngler** [UltimMC/Launcher#275]
### Operating System

Linux

### Description of bug

I tried installing the launcher and it went well but when I tried to start the game it gave me some errors, I searched them up online and found out its probably because I have a headless version of openjdk 8 intalled

So I uninstalled it and downloaded the openjdk version that inst headless but no matter the version the file wont open anymore even when I uninstalled and installed it countless of time I gave it permissions and reproduced all of the steps but it still wont open

### Steps to reproduce

- Install mmc-cracked-lin64.exe

- Extract the file

- Move it to /home

- Give executable permission to the 'UltimMC' file and 'bin/UltimMC' manually

- Try to launch 'bin/UltimMC'

(The last time I did this the launcher opened but it doesnt now)
(Also Im using java 8 for playing in older versions, maybe thats the issue idk)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by dadudeme** [comment]
If you are playing a recent version check in the option of your instance that you are running the correct java version. You need java 17 for 1.16 onwards.

Simply install both versions and select the correct one on instance by instance basis.
This is how I solved this issue on normal MultiMC.
