### ISSUE TITLE
"Failed to upload skin"

### ISSUE THREAD

**Issue by Henrickbr** [UltimMC/Launcher#276]
### Operating System

Windows

### Description of bug

when I upload a skin I get this error  "Failed to upload skin"

### Steps to reproduce

![skin rique](https://github.com/UltimMC/Launcher/assets/134116683/64c9f50d-9e9f-4cd1-8d33-2e05fff43448)

### Suspected cause

i really don't know what to do

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by missitaxd** [comment]
same thing

**Comment by Raidtron** [comment]
same,

**Comment by thebashforkbomber** [comment]
This is a mod to make cracked minecraft
Its literally disconnects  between the real mojang login database and connects you to your localhost database which makes the cracked client

**Comment by tobycm** [comment]
Solution is to use [MultiMC](https://github.com/MultiMC/Launcher/) instead

**Comment by Neptune650** [comment]
This feature is only available for Mojang/Microsoft accounts.
