### ISSUE TITLE
Minecraft crashed when launching packwiz pre-launch command

### ISSUE THREAD

**Issue by fathulfahmy** [UltimMC/Launcher#277]
### Description of bug

I am trying to create an auto-update instance through packwiz jar, the mods are successfully installed. However, the game has crashed.

**Log file:** https://paste.ee/p/nzDkd

**Expected behavior:** instance launch with packwiz auto-update jar

[View packwiz issue thread](https://github.com/packwiz/packwiz-installer/issues/61#issue-1734400650)

### Steps to reproduce

1. Launch MultiMC/UltiMC
2. Add instance > 1.19.2
3. Edit instance > Version > Install Fabric
4. Download packwiz-installer-bootstrap.jar and place it in `.minecraft` folder
5. Edit instance > Settings > Custom Commands > Pre-launch command: `"$INST_JAVA" -jar packwiz-installer-bootstrap.jar https://raw.githubusercontent.com/fathulfahmy/not-another-modpack/main/packwiz/not-another-optifine-modpack/pack.toml`
6. Launch instance

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
Should be fixed now.
