### ISSUE TITLE
How do I get the old badge back?

### ISSUE THREAD

**Issue by QueenUlyana** [UltimMC/Launcher#279]
After today's update, my icon has changed. Although I play on 1.19.4 (1.20 not downloaded). How to get back the old one?
![2023-06-08_184421](https://github.com/UltimMC/Launcher/assets/83131824/f763de4e-9ee9-4046-9674-6955bbc20add)

**Comment by QueenUlyana** [comment]
![6jqI_kPCcFY](https://github.com/UltimMC/Launcher/assets/83131824/fe1d0d98-650a-431a-a88c-37d17a547684)

**I really want the old icons back.**

**Comment by QueenUlyana** [comment]
@Neptune650

**Comment by tobycm** [comment]
ask mojang, this is not related to UltimMC or MultiMC developers

**Comment by QueenUlyana** [comment]
> 

Clearly. I found a mod that helps solve this problem.
