### ISSUE TITLE
Ely.by account connect tutorial?

### ISSUE THREAD

**Issue by thebashforkbomber** [UltimMC/Launcher#280]
i don't know how please someone tell me

**Comment by Wiener234** [comment]
create an Account on Ely.by and then go under settings->account->Add Account enter your Ely.by username and Password and you are done

**Comment by Katayo0** [comment]
> create an Account on Ely.by and then go under settings->account->Add Account enter your Ely.by username and Password and you are done

it isnt working, i tried with nickname and with email, skin doenst apply.

**Comment by raptr45** [comment]
yeah, the skin won't be applied for me either.
