### ISSUE TITLE
Can't open on linux Ubuntu 

### ISSUE THREAD

**Issue by thebashforkbomber** [UltimMC/Launcher#281]
### Operating System

Linux

### Description of bug

former executable script crashes upon launch

### Steps to reproduce

- Download the linux version
- Extract it to /home/gamers/Documents/linux/UltimMC
- Open UltimMC (Folder) with terminal
- chmod -x UltimMC
- Open UltimMC (the file that was chmod'ed)
- Nothing happens

### Suspected cause

Random ass exits

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DestroyerAce** [comment]
@1nfameArts You have to run `chmod +x <file>` to make it executable. `-x` is used to remove executable permissions and `+x` is used to give it executable permissions

**Comment by Neptune650** [comment]
Please use the deb package.
