### ISSUE TITLE
Launcher Issue

### ISSUE THREAD

**Issue by Anthonioe** [UltimMC/Launcher#286]
### Description of bug

i can launch multiple mods like pixelmon or rlcraft or all the mods and none have an issue, but the second i go to sky factory 4 it breaks instantly giving me multiple errors

### Steps to reproduce

no idea why it happens to sky factory only specifically, hope someone can tell me what is causing this issue

### Suspected cause

UltimMC version: 0.7.0-custom

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.66.218.34, 18.66.218.18, 18.66.218.108, 18.66.218.122]

session.minecraft.net resolves to:
    [13.107.246.43, 13.107.213.43]

textures.minecraft.net resolves to:
    [13.107.246.43, 13.107.213.43]

api.mojang.com resolves to:
    [13.107.253.43, 13.107.226.43]

Minecraft folder is:
C:/Users/pcstar/Downloads/Compressed/UltimMC/instances/Sky Factory 4 4.2.4/minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 20.0.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/pcstar/Downloads/Compressed/UltimMC/instances/Sky Factory 4 4.2.4/natives

Using system OpenAL.

Libraries:
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860-universal.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/pcstar/Downloads/Compressed/UltimMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔️] Advancement_Book-1.12-1.0.3.jar
  [✔️] ae2stuff-0.7.0.4-mc1.12.2.jar
  [✔️] AnimalCrops-1.12.2-0.2.0.jar
  [✔️] Apotheosis-1.12.2-1.12.5.jar
  [✔️] AppleSkin-mc1.12-1.0.14.jar
  [✔️] appliedenergistics2-rv6-stable-7.jar
  [✔️] Aroma1997Core-1.12.2-2.0.0.2.b167.jar
  [✔️] AromaBackup-1.12.2-3.0.0.0.b132.jar
  [✔️] astralsorcery-1.12.2-1.10.27.jar
  [✔️] BarrelsDrumsStorageAndMore-0.0.24.jar
  [✔️] base-1.12.2-3.13.0.jar
  [✔️] Baubles-1.12-1.5.2.jar
  [✔️] bdlib-1.14.3.12-mc1.12.2.jar
  [✔️] bedpatch-2.2-1.12.2.jar
  [✔️] BetterAdvancements-1.12.2-0.1.0.77.jar
  [✔️] BiblioCraft[v2.4.5][MC1.12.2].jar
  [✔️] BNBGamingCore-1.12.2-0.12.0.jar
  [✔️] BNBGamingLib-1.12.2-2.17.6.jar
  [✔️] bonsaitrees-1.1.4-b170.jar
  [✔️] Bookshelf-1.12.2-2.3.590.jar
  [✔️] BouncyCreepers-0.0.4.jar
  [✔️] BuildingGadgets-2.8.3.jar
  [✔️] CalmDownZombieGuy-1.12.2-1.0.0.jar
  [✔️] CarryOn MC1.12.2 v1.12.3.jar
  [✔️] Ceramics-1.12-1.3.7b.jar
  [✔️] Chargers-1.12.2-1.2.0.4.jar
  [✔️] ChineseWorkshop-1.12.2_1.2.6.jar
  [✔️] Chisel-MC1.12.2-1.0.2.45.jar
  [✔️] chiselsandbits-14.33.jar
  [✔️] ClickMachine-1.12.2-1.2.0.jar
  [✔️] ClientTweaks_1.12.2-3.1.11.jar
  [✔️] Clumps-3.1.2.jar
  [✔️] CodeChickenLib-1.12.2-3.2.3.358-universal.jar
  [✔️] CoFHCore-1.12.2-4.6.6.1-universal.jar
  [✔️] CoFHWorld-1.12.2-1.4.0.1-universal.jar
  [✔️] ColouredTooltips-1.12.2-1.0.7.jar
  [✔️] CommonCapabilities-1.12.2-2.4.6.jar
  [✔️] compactmachines3-1.12.2-3.0.18-b278.jar
  [✔️] CompactStorage-3.1-12.jar
  [✔️] ComPatchedStorage-1.12.2-1.6.0.jar
  [✔️] conarm-1.12.2-1.2.5.9.jar
  [✔️] ContentTweaker-1.12.2-4.9.1.jar
  [✔️] Controlling-3.0.9.jar
  [✔️] CookingForBlockheads_1.12.2-6.5.0.jar
  [✔️] CraftTweaker2-1.12-4.1.20.574.jar
  [✔️] CTM-MC1.12.2-1.0.2.31.jar
  [✔️] Cucumber-1.12.2-1.1.3.jar
  [✔️] culinaryconstruct-1.3.4.jar
  [✔️] CustomMainMenu-MC1.12.2-2.0.9.1.jar
  [✔️] Cyclic-1.12.2-1.20.3.jar
  [✔️] CyclopsCore-1.12.2-1.6.4.jar
  [✔️] DarkUtils-1.12.2-1.8.230.jar
  [✔️] deepmoblearning-1.12.2-2.5.4-universal.jar
  [✔️] DefaultOptions_1.12.2-9.2.8.jar
  [✔️] DimensionStages-1.12.2-2.0.23.jar
  [✔️] DragonMurder-1.12.2-1.0.1.jar
  [✔️] ElevatorMod-1.12.2-1.4.2.jar
  [✔️] EnchantmentDescriptions-1.12.2-1.1.15.jar
  [✔️] EnderCore-1.12.2-0.5.76.jar
  [✔️] endercrop-1.12.2-1.6.0.jar
  [✔️] EnderStorage-1.12.2-2.4.6.137-universal.jar
  [✔️] enderutilities-1.12.2-0.7.15.jar
  [✔️] ExtendedCrafting-1.12.2-1.5.6.jar
  [✔️] ExtraCells-1.12.2-2.6.5.jar
  [✔️] FancyBlockParticles-1.12.x-2.4.1.jar
  [✔️] FarmingForBlockheads_1.12.2-3.1.28.jar
  [✔️] FastFurnace-1.12.2-1.3.1.jar
  [✔️] FastWorkbench-1.12.2-1.7.3.jar
  [✔️] FenceOverhaul-1.3.4.jar
  [✔️] findme-1.12.2-1.1.0-8.jar
  [✔️] fluxnetworks-1.12.2-4.0.14-31.jar
  [✔️] foamfix-0.10.14-1.12.2.jar
  [✔️] Forgelin-1.8.4.jar
  [✔️] ForgeMultipart-1.12.2-2.6.2.83-universal.jar
  [✔️] ForgivingVoid_1.12.2-1.1.0.jar
  [✔️] GameStages-1.12.2-2.0.123.jar
  [✔️] Guide-API-1.12-2.1.8-63.jar
  [✔️] Headcrumbs-1.12.2-2.0.5.17.jar
  [✔️] HorsePower-1.12.2-2.6.4.74.jar
  [✔️] HuntingDimension-1.12.2-1.0.42.jar
  [✔️] HurtAnimationRemover-1.12.2-1.0.0.jar
  [✔️] Hwyla-1.8.26-B41_1.12.2.jar
  [✔️] HydroGel-1.12.2-1.1.0.jar
  [✔️] iChunUtil-1.12.2-7.1.4.jar
  [✔️] incontrol-1.12-3.9.16.jar
  [✔️] industrialforegoing-1.12.2-1.12.13-237.jar
  [✔️] Inspirations-1.12.2-0.2.9.jar
  [✔️] IntegratedDynamics-1.12.2-1.1.6.jar
  [✔️] IntegratedTunnels-1.12.2-1.6.11.jar
  [✔️] inventorysorter-1.12.2-1.13.357.jar
  [✔️] IronJetpacks-1.12-2-1.1.0.jar
  [✔️] ItemStages-1.12.2-2.0.51.jar
  [✔️] jei_1.12.2-4.15.0.295.jar
  [✔️] journeymap-1.12.2-5.7.1.jar
  [✔️] KleeSlabs_1.12.2-5.4.12.jar
  [✔️] LimitlessStructureBlocks-1.12.2-1.1.0.jar
  [✔️] LoadingScreens-1.12.2-0.3.1.jar
  [✔️] lostcities-1.12-2.0.22.jar
  [✔️] malisiscore-1.12.2-6.5.1.jar
  [✔️] malisisdoors-1.12.2-7.3.0.jar
  [✔️] Mantle-1.12-1.3.3.55.jar
  [✔️] MatterOverdrive-1.12.2-0.7.1.0-universal.jar
  [✔️] mcjtylib-1.12-3.5.4.jar
  [✔️] MCMultiPart-2.5.3.jar
  [✔️] Mekanism-1.12.2-9.8.3.390.jar
  [✔️] MekanismGenerators-1.12.2-9.8.3.390.jar
  [✔️] Mercurius-1.12.2.jar
  [✔️] MobGrindingUtils-0.3.13.jar
  [✔️] MobStages-1.12.2-2.0.13.jar
  [✔️] modtweaker-4.0.18.jar
  [✔️] MoreBuckets-1.12.2-1.0.4.jar
  [✔️] More-Cauldrons-1.4.6.jar
  [✔️] moreoverlays-1.15.1-mc1.12.2.jar
  [✔️] Morpheus-1.12.2-3.5.106.jar
  [✔️] MouseTweaks-2.10-mc1.12.2.jar
  [✔️] mpbasic-1.12.2-1.4.11.jar
  [✔️] MPUtils-1.12.2-1.5.7.jar
  [✔️] MTLib-3.0.6.jar
  [✔️] mystcraft-1.12.2-0.13.7.06.jar
  [✔️] MysticalAgradditions-1.12.2-1.3.2.jar
  [✔️] MysticalAgriculture-1.12.2-1.7.5.jar
  [✔️] Neat 1.4-17.jar
  [✔️] NuclearCraft-2.18u-1.12.2.jar
  [✔️] ocxnetdriver-1.0.3-b17.jar
  [✔️] ogdragon-1.12.2-0.1.4.jar
  [✔️] OpenComputers-MC1.12.2-1.7.5.192.jar
  [✔️] OreExcavation-1.4.150.jar
  [✔️] Parabox-1.12.2-2.0.0.jar
  [✔️] Patchouli-1.0-20.jar
  [✔️] PickleTweaks-1.12.2-2.1.3.jar
  [✔️] PipeMaster-1.0.2-b8.jar
  [✔️] Placebo-1.12.2-1.6.0.jar
  [✔️] PlaneFix-1.12.2-1.0.0.jar
  [✔️] PortalGun-1.12.2-7.1.0.jar
  [✔️] practicallogistics2-1.12.2-3.0.8-11.jar
  [✔️] Prestige-1.12.2-1.1.58.jar
  [✔️] primitivecrafting-1.12.2-1.4.4.7.jar
  [✔️] ProjectE-1.12.2-PE1.4.1.jar
  [✔️] ProportionalDestructionParticles-1.12.2-1.2.4.jar
  [✔️] rangedpumps-0.5.jar
  [✔️] realfilingcabinet-1.12-0.2.0.21.jar
  [✔️] reauth-3.6.0.jar
  [✔️] RecipeStages-1.1.3.jar
  [✔️] RedstoneFlux-1.12-2.1.1.1-universal.jar
  [✔️] ResourceHogs-1.12.2-1.0.14.jar
  [✔️] ResourceLoader-MC1.12.1-1.5.3.jar
  [✔️] rftoolspower-1.12-1.2.0.jar
  [✔️] rustic-1.1.4.jar
  [✔️] simplegenerators-1.12.2-2.0.20.2.jar
  [✔️] SimpleStorageNetwork-1.12.2-1.7.10.jar
  [✔️] simpletomb-1.12.2-1.0.0.jar
  [✔️] SkyBonsais-1.0.1.jar
  [✔️] SkyGrid-1.1.7.jar
  [✔️] SkyOrchards-0.0.12.jar
  [✔️] Slab_Machines-1.0.7.jar
  [✔️] SlimyBoyos-1.0.0.jar
  [✔️] SmoothFont-mc1.12.2-2.1.2.jar
  [✔️] Snad-1.12.1-1.7.09.16a.jar
  [✔️] sonarcore-1.12.2-5.0.19-20.jar
  [✔️] SqueezerPatch-1.12.2-1.0.0.jar
  [✔️] statues-1.12.X-0.8.9.2.jar
  [✔️] stg-1.12.2-1.2.3.jar
  [✔️] StuffASockInIt-1.12.2-1.1.30.jar
  [✔️] supersoundmuffler-revived_1.12.2_1.0.2.10.jar
  [✔️] Surge-1.12.2-2.0.77.jar
  [✔️] Sync-1.12.2-7.1.0.jar
  [✔️] TallGates-1.12.2-1.0.0.1.jar
  [✔️] TConstruct-1.12.2-2.13.0.183.jar
  [✔️] TelePastries-0.3.4.jar
  [✔️] tesla-core-lib-1.12.2-1.0.18.jar
  [✔️] ThermalDynamics-1.12.2-2.5.6.1-universal.jar
  [✔️] ThermalFoundation-1.12.2-2.6.7.1-universal.jar
  [✔️] ThermalInnovation-1.12.2-0.3.6.1-universal.jar
  [✔️] TinkersComplement-1.12.2-0.4.3.jar
  [✔️] TinkerToolLeveling-1.12.2-1.1.0.jar
  [✔️] tinyprogressions-1.12.2-3.3.34-Release.jar
  [✔️] TipTheScales-1.12.2-1.0.4.jar
  [✔️] Toast Control-1.12.2-1.8.1.jar
  [✔️] togetherforever-1.12.2-1.0.12-22.jar
  [✔️] Topography-1.12.2-1.14.2.jar
  [✔️] torchmaster_1.12.2-1.8.5.0.jar
  [✔️] Translocators-1.12.2-2.5.2.81-universal.jar
  [✔️] TreeGrowingSimulator2017-1.0.1.jar
  [✔️] Triumph-1.12.2-3.19.2.jar
  [✔️] twilightforest-1.12.2-3.11.1021-universal.jar
  [✔️] Twitchcrumbs_1.12.2-3.0.4.jar
  [✔️] Uppers-0.0.6.jar
  [✔️] valkyrielib-1.12.2-2.0.20.1.jar
  [✔️] ViesCraft-1.12.2-5.9.16.jar
  [✔️] Waddles-1.12.2-0.6.0.jar
  [✔️] WailaStages-1.12.2-2.0.24.jar
  [✔️] walljump-1.12.2-1.3.2.jar
  [✔️] Wawla-1.12.2-2.6.275.jar
  [✔️] weirdinggadget-1.12.2-2.1.16-universal.jar
  [✔️] witherCrumbs-1.12.2-0.11.jar
  [✔️] WorldBook-1.0.0.jar
  [✔️] worldutils-1.12.2-0.4.2.jar
  [✔️] XL-Food-Mod-1.12.2-1.9.2.jar
  [✔️] xnet-1.12-1.8.2.jar
  [✔️] YNot-0.2.4.jar
  [✔️] yoyos_1.12.2-1.3.3.25.jar
  [✔️] zenstages-0.5.0.jar

Params:
  --username  --version 1.12.2 --gameDir C:/Users/pcstar/Downloads/Compressed/UltimMC/instances/Sky Factory 4 4.2.4/minecraft --assetsDir C:/Users/pcstar/Downloads/Compressed/UltimMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-javaagent:C:/Users/pcstar/Downloads/Compressed/UltimMC/injectors/authlib-injector-1.2.3.jar=http://localhost:52629, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1536m, -Duser.language=en]

Minecraft process ID: 10268

[authlib-injector] [INFO] Logging file: C:\Users\pcstar\Downloads\Compressed\UltimMC\instances\Sky Factory 4 4.2.4\minecraft\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.3
[authlib-injector] [INFO] Authentication server: http://localhost:52629
[authlib-injector] [WARNING] You are using HTTP protocol, which is INSECURE! Please switch to HTTPS if possible.
Using onesix launcher.

Failed to start Minecraft:
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 06 Jul 2023 04:05:57 -1100

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by tncc2k** [comment]
I also can't launch
(Launched instance in online mode)

**Comment by Neptune650** [comment]
Likely not related to UltimMC at all.
