### ISSUE TITLE
Nightly link don't work

### ISSUE THREAD

**Issue by AlofBronco** [UltimMC/Launcher#287]
### Operating System

Windows

### Description of bug

The link is expired

### Steps to reproduce

Click on any link in pre-built binaries

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by androidghosh** [comment]
Same issue 

![image](https://github.com/UltimMC/Launcher/assets/17355109/85a66af0-7743-4ccd-adca-79e75e62b161)

**Comment by archbtww** [comment]
Same issue

**Comment by no-comm** [comment]
Same issue

**Comment by AlofBronco** [comment]
Does developers abonded project?

**Comment by Weigurde** [comment]
it's not necessarily abandoned, it still works if you compile manually - the download link is only broken because there hasn't been any changes made in 90 days

**Comment by Day-OS** [comment]
https://github.com/UltimMC/Launcher/actions/runs/5261542745

**Comment by 0Shum0** [comment]
> https://github.com/UltimMC/Launcher/actions/runs/5261542745

You solved all my problems)

**Comment by abarrackz** [comment]
Can someone update the download link ?

**Comment by Ladha979** [comment]
The main nightly link has been fixed
