### ISSUE TITLE
Cannot connect to a server

### ISSUE THREAD

**Issue by didi270307** [UltimMC/Launcher#289]
### Operating System

Windows

### Description of bug

![image](https://github.com/UltimMC/Launcher/assets/141257891/e43095be-da7f-4204-909a-d0504c6f602f)
I'm getting this error when trying to join servers 

### Steps to reproduce

Connect to a server

### Suspected cause

Could it be because I didn't let java get firewall permissions?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
You need to give Java access through your Firewall.
