### ISSUE TITLE
Linux file is not there

### ISSUE THREAD

**Issue by GorEldeen** [UltimMC/Launcher#291]
### Operating System

_Linux_

### Description of bug

I want to download the pre-built linux version of the launcher but it seems it has been deleted?

### Steps to reproduce

Try to visit the Linux version download link

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
https://github.com/UltimMC/Launcher/actions/runs/5261542745
