### ISSUE TITLE
The download links are no longer available

### ISSUE THREAD

**Issue by LeggyLad** [UltimMC/Launcher#292]
### Description of bug

When clicking on any of the download links, the website gives an error and says that because the files are older than 90 days they are expired.

### Steps to reproduce

just click the download link

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
https://github.com/UltimMC/Launcher/actions/runs/5261542745

**Comment by Ladha979** [comment]
> https://github.com/UltimMC/Launcher/actions/runs/5261542745

Hi, thankyou for linking the build compilation. I'm not that tech savvy but I think the files are still inaccessible to the public. I tried opening the link you gave but I can't find a way to download the compiled files itself, and the links on the main github page  (e.g https://nightly.link/UltimMC/Launcher/workflows/main/develop) are outdated and lead to errors. I think those need to be updated to point to the correct directory?

Edit: Yeah I just didn't know how to access it. Putting the link you provided into https://nightly.link/ works and gives links to the updated builds

https://nightly.link/UltimMC/Launcher/actions/runs/5261542745

**Comment by Packjackisback** [comment]
download the artifacts
