### ISSUE TITLE
Launcher icon broken & crashes

### ISSUE THREAD

**Issue by Darthagnon** [UltimMC/Launcher#293]
### Description of bug

The icon on UltimMC.exe is broken while running.
![y6tZz8HZvb](https://github.com/UltimMC/Launcher/assets/20792748/08585e68-c84d-47f0-8275-09992189f274)

Also, it unpredictably crashes when closing the program.

### Steps to reproduce

Run UltimMC. The icon on the EXE will break on the taskbar and titlebar.

Close UltimMC. It will unpredictably crash, rather than closing cleanly.

### Suspected cause

Icon could be some Qt icon embedding issue. I'm on Windows 10.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
same

**Comment by Darthagnon** [comment]
This issue is a duplicate of https://github.com/UltimMC/Launcher/issues/170

**Comment by Neptune650** [comment]
Duplicate of #170
