### ISSUE TITLE
List Update failed

### ISSUE THREAD

**Issue by bingchilliner** [UltimMC/Launcher#294]
### Description of bug

i was succesfuly installed but than when i add new intances they said "no version are currently avalible"

### Steps to reproduce

i think that my account was ment to cracked so the intances wouldt load

### Suspected cause

i dont know how did this happen i just thought they will give me the list of it

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
Unable to reproduce.
