### ISSUE TITLE
Fake UltimMC Clone

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [UltimMC/Launcher#295]
[This youtuber](https://www.youtube.com/@BansaFanchik/) copied this launcher src  (Without proper fork), put MIT license over original license and claiming that launcher is made by him in readme (He wrote `By Baner` at the bottom of readme) and in same time he uploaded binaries to his guilded server and put links to those binaries in [his repository](https://github.com/BANSAFAn/UltimMC)

**Comment by alexsovi** [comment]
His words:
![translated](https://github.com/UltimMC/Launcher/assets/101274903/ff0cb6d9-c656-42ba-8050-f30f10b00818)
![original](https://github.com/UltimMC/Launcher/assets/101274903/628c9a7c-31cc-4233-96e9-61eafa032243)
Then, he banned me.

**Comment by MrMasrozYTLIVE** [comment]
Also he deleted my  Issue I made  in [his repository](https://github.com/BANSAFAn/UltimMC) where I was asking is he made the launcher or no

**Comment by Neptune650** [comment]
Thanks for informing us, however they don't seem to have done any malicious changes and their community seems small enough for this to not matter.
