### ISSUE TITLE
Can't join LAN servers hosted by local account as another local account

### ISSUE THREAD

**Issue by DeenOConnor** [UltimMC/Launcher#296]
### Operating System

Windows 10

### Description of bug

When joining a local server hosted with local account as another local account you can't join. Also you can't resolve any LAN servers hosted this way, and all that were manually added appear offline regardless of their actual status.
Possible solutions that google shows all didn't work or were describing a different issue.
This issue seemingly doesn't appear when using version 0.6.12 (built manually from multimc-cracked repo, and this is the only old version i have), and if i host vanilla server and someone else joins from 0.6.12 they can actually play on my server, but not vice versa.
I don't know if and where i can get older builds of multimc to pinpoint the exact version when this problem appeared, but i'm willing to test if there's a way (i could try building after each commit but this sounds like a lot of unnecessary pain).

### Steps to reproduce

0. Install minecraft (consistent with 1.20.1, both vanilla and modded)
1. Create and join a world in singleplayer as a local account
2. Open to LAN
3. Another UltimMC user with a local account (same version and platform) tries to join
4. Failed to log in: The authentication servers are currently not reachable. Please try again.

### Suspected cause

This problem is likely related to #240 but i'm not sure if it's the same or just a similar one.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Wiener234** [comment]
If the server is hosted via the server.jar or something similar and not just a world opened to Lan, then try going into server.properties and changing online-mode to false.
That way the server doesn't check if there is a Mojang Account or Microsoft Account behind it.

**Comment by DeenOConnor** [comment]
No, the server is not a dedicated server, it's a single player world open to LAN from the pause menu as stated in the description.
And if it was a dedicated server, i don't think using an older version would've done anything.
Also i'm aware of online-mode, but i don't think i can do that to my "Open to LAN" server, and even if i could, i doubt that's the issue.

**Comment by Wiener234** [comment]
Sorry I missed the part with opening to lan. Setting a server to offline mode. Would indeed fix the problem, cause then it does not check if you are using an office Minecraft account. But I have now idea how to apply that to lan.

**Comment by qwerty12356-wart** [comment]
I have encountered this before and you can fix this by installing a LAN server setting mod.

**Comment by DeenOConnor** [comment]
Probably, but then why does the issue disappear when everyone playing just uses an older version of the launcher? Same world, same game instance, but everything starts working again.

**Comment by qwerty12356-wart** [comment]
I dont know for sure but this is probably a flaw in the fix for #240

**Comment by DeenOConnor** [comment]
I tested the most recent version and the issue doesn't appear anymore
