### ISSUE TITLE
Improvements to the packaging

### ISSUE THREAD

**Issue by j3bx** [UltimMC/Launcher#298]
### Description of bug

I made a flatpak of this fork which works, but since the program uses the same location as the executable to store the data and the location is read only, the program can't start, is there a way of choosing an arbitrary data folder

### Steps to reproduce

Make a flatpak using the artifacts available from the readme

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
There are official AUR and .deb packages now, please check them to see how this is done.
