### ISSUE TITLE
/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found

### ISSUE THREAD

**Issue by WizardlyBump17** [UltimMC/Launcher#299]
### Operating System

Linux

### Description of bug

PC specs: 
![image](https://github.com/UltimMC/Launcher/assets/38295327/9077b823-3613-4e6b-a51f-9cfb830ce9a4)

When I try to run the launcher, it does not start and when I launch it via terminal, this is shown:
```
davi@davi:~/Downloads/UltimMC$ ./UltimMC 
Launcher Dir: /home/davi/Downloads/UltimMC
No missing dependencies found.
/home/davi/Downloads/UltimMC/UltimMC: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/davi/Downloads/UltimMC/UltimMC)
/home/davi/Downloads/UltimMC/UltimMC: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/davi/Downloads/UltimMC/UltimMC)
/home/davi/Downloads/UltimMC/UltimMC: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/davi/Downloads/UltimMC/bin/libLauncher_quazip.so)
/home/davi/Downloads/UltimMC/UltimMC: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/davi/Downloads/UltimMC/bin/libLauncher_nbt++.so)
/home/davi/Downloads/UltimMC/UltimMC: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/davi/Downloads/UltimMC/bin/libLauncher_iconfix.so)
/home/davi/Downloads/UltimMC/UltimMC: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/davi/Downloads/UltimMC/bin/libLauncher_rainbow.so)
```
The original MultiMC launcher starts as expected, but UltimMC does not

### Steps to reproduce

Download the launcher and tries to launch it via the terminal

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by WizardlyBump17** [comment]
I found a solution, but it is the user that must solve it, which shouldn't happen because the application should work without any errors.

How to solve it as the user: (I spent 2 weeks on that and I am not familiar with software programming so maybe some steps may be redundant)
1. Clone and build the OpenSSL yourself, but install it in a different path than the default (https://github.com/openssl/openssl/blob/master/INSTALL.md, https://github.com/openssl/openssl/blob/master/INSTALL.md#installing-openssl, https://github.com/openssl/openssl/blob/master/INSTALL.md#installing-to-a-different-location)
2. Clone and build the Qt (see the next step before running the `./configure`) (https://wiki.qt.io/Building_Qt_5_from_Git, https://wiki.qt.io/Building_Qt_5_from_Git#Getting_the_source_code)
3. Instead of using the `./configure` provided by the wiki, use this: `./configure -openssl-linked -D OPENSSL_ROOT_DIR=<path where you built the OpenSSL>/include -DFEATURE_openssl_linked=ON`
4. Proceed with the build steps provided by the Qt wiki (it will take a LONG time)
5. Clone the UltimMC repo (https://github.com/UltimMC/Launcher/blob/develop/BUILD.md#getting-the-source)
6. Follow the https://github.com/UltimMC/Launcher/blob/develop/BUILD.md#building-from-command-line to build the launcher (but skip the clone part, of course) 
7. When building, some errors may happen. The ones that happened with me were about QDebug and QSslError. To fix them, just add `#include <the class>`, in the files that had problems, among with the another `#include` lines
8. I dont know if this is necessary, but I did it. Follow this part https://github.com/UltimMC/Launcher/blob/develop/BUILD.md#loading-the-project-in-qt-creator-optional (you must install the QtCreator software) and you should have a `build-UltimMC-Qt_5_15_10_in_PATH_Qt_5_15_10-Release` folder where you can execute the `UltimMC` file and be happy

**Comment by Neptune650** [comment]
Not particularly sure why it wouldn't work in your system, and why rebuilding it fixed it, does this error still happen?
