### ISSUE TITLE
Crash (IllegalArgumentException: Invalid UUID string: "")

### ISSUE THREAD

**Issue by ghost** [UltimMC/Launcher#303]
### Operating System

Windows

### Description of bug

As soon as you launch an instance it crashes with an `IllegalArgumentException` of `Invalid UUID string: `.
Full game log: https://paste.ee/p/vT4so

### Steps to reproduce

Launch an instance with the latest version from https://nightly.link/UltimMC/Launcher/workflows/main/develop/mmc-cracked-win32.zip

### Suspected cause

It appears like the UUID is not being set correctly. I'm not familiar with the codebase and the inner workings of MultiMC/UtilmMC so I can't say for sure.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by APTEM591** [comment]
Same problem. When trying to launch 1.20.2 only

**Comment by LoneDev6** [comment]
I confirm it's not compatible with 1.20.2

**Comment by bassmannate** [comment]
Same issue but on Linux. 1.20.1 works fine but 1.20.2 is not compatible yet.

**Comment by stucq** [comment]
the error comes about when mc's main function is [called](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/libraries/launcher/org/multimc/onesix/OneSixLauncher.java#L164), and so presumably the error comes about by the fact that a uuid command line argument is necessary and it for some reason isn't supplied

**Comment by stucq** [comment]
update: `--uuid` specifically is parsed from the launch script (parsed by [this](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/libraries/launcher/org/multimc/EntryPoint.java#L82C19-L82C19) function). the `--uuid` parameter specifically is generated by [this](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/launcher/minecraft/MinecraftInstance.cpp#L426) function

**Comment by stucq** [comment]
update 2: [this](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/launcher/minecraft/auth/MinecraftAccount.cpp#L246) line defines the UUID. it calls [this](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/launcher/minecraft/auth/MinecraftAccount.h#L125) function to do so, which in turn calls [this](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/launcher/minecraft/auth/AccountData.cpp#L416) function, the value of which is defined on [this](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/launcher/minecraft/auth/AccountData.cpp#L294) line, which retrieves it from the list profiles accessed [here](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/launcher/minecraft/auth/AccountData.cpp#L254C24-L254C24). that function is called by [this](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/launcher/minecraft/auth/MinecraftAccount.cpp#L39C50-L39C50) function, which is in turn called by [this](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/launcher/minecraft/auth/AccountList.cpp#L496) function, which is in turn called by [this](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/launcher/minecraft/auth/AccountList.cpp#L472C20-L472C20) function, which gets its data from [this](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/launcher/minecraft/auth/AccountList.cpp#L625) function, which is called by [this](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/launcher/Application.cpp#L922) function on `accounts.json`

**Comment by stucq** [comment]
anyways i believe you just need to define `ygg.id` for all accounts though i'm not 100% sure. testing rn

**Comment by stucq** [comment]
update 3: every time i try to manually update accounts.json with the UUID, it is automatically rewritten and removed. so i think that's the source of the problem. looking into it right now

**Comment by stucq** [comment]
update 4: it's written by [this](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/launcher/minecraft/auth/AccountList.cpp#L554) function which calls [this](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/launcher/minecraft/auth/MinecraftAccount.cpp#L73) function which calls [this](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/launcher/minecraft/auth/AccountData.cpp#L349) function. anyways it seems the UUID should actually be kept in `type` (which is `dummy`), which comes from [this](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/launcher/minecraft/auth/AuthProviders.cpp#L27) function which gets the UUID from [this](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/launcher/minecraft/auth/providers/DummyAuthProvider.h#L17) function, which correctly returns `"dummy"`. so we need to find the point of disconnect but from here that shouldn't be very difficult at all

**Comment by stucq** [comment]
update 5: [i believe i've found the culprit](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/launcher/minecraft/auth/AccountData.cpp#L115)

**Comment by stucq** [comment]
update 6: so i'm pretty sure what's broken is that a `MinecraftProfile` isn't created for each new account

**Comment by stucq** [comment]
update 7: yep, found it. MinecraftAccount [doesn't initialize](https://github.com/UltimMC/Launcher/blob/6883ec603ce14ce76dac90120b1490c67079bf90/launcher/minecraft/auth/MinecraftAccount.cpp#L55) `data.minecraftProfile`, which leaves `data.minecraftProfile.id` as `""`, leading to the error

**Comment by stucq** [comment]
update 8: fixed #310
