### ISSUE TITLE
Microsoft account

### ISSUE THREAD

**Issue by skallistey** [UltimMC/Launcher#304]
### Operating System

Windows

### Description of bug

I use a Microsoft account to log into Minecraft, you don’t have this option, what should I do?

### Steps to reproduce

[https://prnt.sc/BPDgUg__Cf7E](url)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DeenOConnor** [comment]
You should use original [MultiMC](https://github.com/MultiMC/Launcher) and ask questions there if you have any, this version was created so you can play without a microsoft account, as stated in [readme](https://github.com/UltimMC/Launcher/tree/develop#readme).
