### ISSUE TITLE
Lots of versions dont work.

### ISSUE THREAD

**Issue by HaydenPlayzMinecraft** [UltimMC/Launcher#306]
### Operating System

_Windows 11_

### Description of bug

whenever i use versions below 1.12 it says, "patch not loaded", and if i click legit anything, UltimMc crashes

### Steps to reproduce

use java 8,
click a version (minecraft 1.8.9 is best)

### Suspected cause

might be because there too old, but idk, because 1.7.10 works fine.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by MedJb** [comment]
i wanna ask. did you change java path in the launcher or instance settings ?

**Comment by Neptune650** [comment]
Unable to reproduce, likely unrelated to UltimMC.
