### ISSUE TITLE
Is it possible to change the UUID for local accounts?

### ISSUE THREAD

**Issue by Hoeze** [UltimMC/Launcher#311]
### Role

I want to keep my official UUID when joining my server

### Suggestion

Set my official UUID

### Benefit

I can turn my server to offline for testing without loosing my permissions, etc.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by MeBadDev** [comment]
No, thats not possible
