### ISSUE TITLE
Game does not open newer versions

### ISSUE THREAD

**Issue by Richardgames807** [UltimMC/Launcher#312]
### Description of bug

UltimMC version: 0.7.0-custom

Launched instance in online mode

authserver.mojang.com resolves to:
    [3.162.247.20, 3.162.247.57, 3.162.247.122, 3.162.247.5]

session.minecraft.net resolves to:
    [13.107.246.33, 13.107.213.33]

textures.minecraft.net resolves to:
    [13.107.246.33, 13.107.213.33]

api.mojang.com resolves to:
    [13.107.213.33, 13.107.246.33]

Minecraft folder is:
C:/Users/esthe/AppData/Roaming/UltimMC/instances/23w43b/.minecraft

Java path is:
C:/Program Files/Java/jdk-19/bin/javaw.exe

Checking Java version...
Java is version 19.0.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/esthe/AppData/Roaming/UltimMC/instances/23w43b/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/com/mojang/authlib/5.0.50/authlib-5.0.50.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/commons-io/commons-io/2.13.0/commons-io-2.13.0.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/net/java/dev/jna/jna-platform/5.13.0/jna-platform-5.13.0.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar
  C:/Users/esthe/AppData/Roaming/UltimMC/libraries/com/mojang/minecraft/23w43b/minecraft-23w43b-client.jar

Native libraries:

Params:
  --username <TOKEN DE ACESSO> --version 23w43b --gameDir C:/Users/esthe/AppData/Roaming/UltimMC/instances/23w43b/.minecraft --assetsDir C:/Users/esthe/AppData/Roaming/UltimMC/assets --assetIndex 10 --uuid  --accessToken <TOKEN DE ACESSO> --userType Local --versionType snapshot

Window size: 854 x 480

Java Arguments:
[-javaagent:C:/Users/esthe/AppData/Roaming/UltimMC/injectors/authlib-injector-1.2.3.jar=http://localhost:51608, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms16384m, -Xmx16384m, -Duser.language=en]

Minecraft process ID: 14580

[authlib-injector] [INFO] Logging file: C:\Users\esthe\AppData\Roaming\UltimMC\instances\23w43b\.minecraft\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.3
[authlib-injector] [INFO] Authentication server: http://localhost:51608
[authlib-injector] [WARNING] You are using HTTP protocol, which is INSECURE! Please switch to HTTPS if possible.
Using onesix launcher.

[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.properties.Property] with [Yggdrasil Public Key Transformer]
Failed to start Minecraft:
java.lang.IllegalArgumentException: Invalid UUID string: 
	at java.base/java.util.UUID.fromString1(UUID.java:280)
	at java.base/java.util.UUID.fromString(UUID.java:258)
	at com.mojang.util.UndashedUuid.fromStringLenient(UndashedUuid.java:14)
	at net.minecraft.client.main.Main.main(SourceFile:151)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
O processo foi encerrado com o código de saída -1 (0xffffffffffffffff).
Lembre-se de que o código de saída e a descrição são insuficientes para diagnosticar problemas!
Sempre envie o log inteiro e não só o código de saída.

### Steps to reproduce

![image](https://github.com/UltimMC/Launcher/assets/149218640/a47235a8-e988-41a8-915f-6cdb25b82b2b)
![image](https://github.com/UltimMC/Launcher/assets/149218640/7e69060a-1fd2-4238-8734-01c27741d4f1)
is this

### Suspected cause

IDK

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by yarik303** [comment]
a patch has already made but wasnt pushed into this build
if u want in pull request u will find smbdy already made a patch/
if u can, compile it
if u cant, use sklauncher or another software (but not some russian shit like klauncher or tlauncher for god sake they have malware)
some people recomend also tlauncher legacy
and old version of tlauncher by old creator without malware but i think it has ads not sure
so ur best bet is to use sklauncher(altho skins will not work) or compile the patch ur self



or buy the game
the options are up to you

**Comment by Neptune650** [comment]
Should be fixed now
