### ISSUE TITLE
can't connect to my ely.by account

### ISSUE THREAD

**Issue by shawchip** [UltimMC/Launcher#313]
i want to get my ely.by account skin but cannot connect it if i try with my username and not the mail
![image](https://github.com/UltimMC/Launcher/assets/96001294/4a3713c4-3375-409f-ae27-be2093ba1319)
but if i put my mail in, it works but changes my username to the mail and not the ely.by accounts username

(sorry if didnt explain it well)

**Comment by shawchip** [comment]
AND even when i connect my ely.by account using my mail i still dont have my skin

**Comment by NerdistRay** [comment]
Same. I can connect to my ely.by account but skins don't work.

**Comment by Neptune650** [comment]
Fixed (by disabling the buttons, since ely.by doesn't provide an API to change skins, just use their web UI)

Also the username issue should be fixed now as well, hopefully
