### ISSUE TITLE
Launcher fails to fetch meta file from https://meta.multimc.org/v1/net.minecraft/index.json

### ISSUE THREAD

**Issue by onenonlyaman** [UltimMC/Launcher#314]
### Operating System

Windows

### Description of bug

I recently downloaded ultimmc's latest pre-built binaries for windows. I have Adoptium Java JRE version 17.0.9.9 installed. 

Error
`List update failed:
Job 'Download of meta file net.minecraft/index.json' failed to process:
https://meta.multimc.org/v1/net.minecraft/index.json
`

### Steps to reproduce

* Start the launcher
* Open "New Instances"
* Get the error

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by sa123321321** [comment]
can confirm

**Comment by onenonlyaman** [comment]
Actually the issue was resolved when I upgraded from Windows 10 to Windows 11. I don't even know why that worked. Closing this issue
