### ISSUE TITLE
Failed to fetch metadata: javax.net.ssl.SSLHandshakeException

### ISSUE THREAD

**Issue by Vik-ROM** [UltimMC/Launcher#315]
### Description of bug

It happens when i run vanilla 1.16.5 ver, and the same with pixelmon modpack.

### Steps to reproduce

https://paste.ee/p/3II9u

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
The paste has been deleted.
