### ISSUE TITLE
Fabric installer: No launcher profile.json found!

### ISSUE THREAD

**Issue by gptlang** [UltimMC/Launcher#317]
### Operating System

Linux

### Description of bug

I'm trying to install the Fabric API but it throws an error:
```
java.lang.RuntimeException: No launcher profile.json found!
```

It succeeded after I made a fake `launcher_profiles.json` file. However, it is not respected by the launcher

### Steps to reproduce

1. Install `1.20.2`
2. Try to install fabric API

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
This is... odd, I'm unable to reproduce it, please reopen with more information if the issue continues
