### ISSUE TITLE
It dose not launch 1.20.2

### ISSUE THREAD

**Issue by scbx99** [UltimMC/Launcher#318]
### Description of bug

Well, my UltimMc can't start Minecraft 1.20.2 and the server that I created was in 1.20.1 but then the server stopped working on 1.20.1 so I upgraded it to 1.20.2 but UltimMc can't launch version 1.20.2

### Steps to reproduce
- Added a new instance
- Launch the instance

### Suspected cause
```
error message: [Yggdrasil Public Key Transformer]
Failed to start Minecraft:
java.lang.IllegalArgumentException: Invalid UUID string: 
	at java.base/java.util.UUID.fromString1(UUID.java:282)
	at java.base/java.util.UUID.fromString(UUID.java:260)
	at com.mojang.util.UndashedUuid.fromStringLenient(UndashedUuid.java:14)
	at net.minecraft.client.main.Main.main(SourceFile:151)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
```
### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Paelor** [comment]
Two reasons. First, 1.20.2 was upgraded to OpenJDK 17.0.8 that would need to be installed and selected under the settings java path section. Second, 1.20.2 was upgraded to LWJGL 3.3.2, which is not an option yet to select in UltimMC. In fact, if you right click on your 1.20.2 instance and click edit instance, it more than likely only shows Minecraft 1.20.2 in the version area box. Usually LWJGL is positioned above the Minecraft version.. for example if you check a previous Minecraft vanilla instance, a LWJGL version is always installed and positioned above the Minecraft client. As of replying to this post, the LWJGL GitHub page has downloads available of 3.3.2 and 3.3.3.. so you would have to manually install LWJGL 3.3.2 until UltimMC is updated to select versions past 3.3.1

**Comment by Raif1** [comment]
How can I install LWJGL manually?

**Comment by Paelor** [comment]
You would have to extract the files located in the downloaded file lwjgl.zip from GitHub to the correct folder locations in your UltimMC directory. Also, you would need to force UltimMC to recognize the new version by editing the instance config file in your 1.20.2 instance folder. Open the instance config file with a text editor and scroll down until you see LWJGLVersion=

You would need to edit to LWJGLVersion=3.3.2  and then save the instance config file. Of course like I said before doing this you would need to extract the files of the 3.3.2 lwjgl.zip to the correct folders in UltimMC.

It would probably be easier for many users if you just wait until one of the users working on UltimMC updates to a new version that fixes the problem as manually updating and configuring files can be tricky to the inexperienced and misplaced files would cause you to have to delete the instance and try over again until you get it right. If you're already asking "How can I install LWJGL manually?" my advice it just wait until an update.

**Comment by lBEASTl** [comment]
Is there any progress on this? i have the same problem but it also happened to me on 1.20.1 and new snapshots of 1.20.3.
