### ISSUE TITLE
 UltimMC Cannot Download Because The File Is Over 90 Days Old So I Have Another Link!

### ISSUE THREAD

**Issue by KienPC1234** [UltimMC/Launcher#319]
## Developer's Build Downloads ##
https://github.com/UltimMC/Launcher/actions/runs/6843330274/job/18605808473
## Full Windows Installer File ##
https://www.mediafire.com/file/32x2ra7hue4vsci/UltimMC.exe/file
https://youtu.be/Y80DfrwMiPo
## Note ##
If You Install The File In The Program Files Folder, Please Run UltimMC Under Admin Or It Will Not Run!

**Comment by KienPC1234** [comment]
I Guarantee No Viruses!

**Comment by piratedlemon** [comment]
Too convenient, I don't trust it. Unless it's from the actual developers, I'm not going to go through with that.

EDIT: This guy, let's call a 'loser', edited their comment with the official link to download, get this, to cover up the shameless sharing of a link to download a fake Ultimc infected with malware. How pathetic lol

**Comment by KienPC1234** [comment]
This installation file was created by me to make it easier to install, but if you want the developer's link, here: https://github.com/UltimMC/Launcher/actions/runs/6843330274 (File at Artifacts)

> Too convenient, I don't trust it. Unless it's from the actual developers, I'm not going to go through with that.

**Comment by KienPC1234** [comment]
![Screenshot 2023-11-21 210405](https://github.com/UltimMC/Launcher/assets/121302025/2b5314c0-3470-4586-ac70-389768af93c6)

**Comment by Paelor** [comment]
or copy the link of the download page from GitHub and paste the link into the search area of the WayBackMachine on archive.org then click on a result that is 91+ days old to download the files that were archived at that time.

**Comment by ghost** [comment]
Hey buddy @KienPC1234 
First, i wanted to say, your English is extremely bad.
Secondly, you're literally on a platform full of developers, and guess what
![Funny virus goes BRRR](https://github.com/UltimMC/Launcher/assets/152000275/7bf4b17c-ca0c-4af5-9f02-085062d3d375)

# No one will fall for that scam bud,

We dont want your shitty trojan, i litteraly made a github account (once again since i've got locked down) just to fucking reply to your stupid virus

**ps: you suck**

**Comment by mirfani340** [comment]
> Hey buddy @KienPC1234 First, i wanted to say, your English is extremely bad. Secondly, you're literally on a platform full of developers, and guess what ![Funny virus goes BRRR](https://private-user-images.githubusercontent.com/152000275/285578561-7bf4b17c-ca0c-4af5-9f02-085062d3d375.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NDU0NjQsIm5iZiI6MTcwMTc0NTE2NCwicGF0aCI6Ii8xNTIwMDAyNzUvMjg1NTc4NTYxLTdiZjRiMTdjLWNhMGMtNGFmNS05ZjAyLTA4NTA2MmQzZDM3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQwMjU5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTAxZDkxOWE3ZmQ0NjJkMjliNjE0ZjJiNTUxOGZhMTk1MTc4ZmRkNWE4ZDAxNzIxZWY5YjRiYjQ4Yjk4MDA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4p1vgZ9ACtf3R7-pc0tP3Ii_EXNQrT-0DZbqL_5MUq8)
> 
> # No one will fall for that scam bud,
> We dont want your shitty trojan, i litteraly made a github account (once again since i've got locked down) just to fucking reply to your stupid virus
> 
> **ps: you suck**

hi, can u provide me with the file hash?

**Comment by ghost** [comment]
> > Hey buddy @KienPC1234 First, i wanted to say, your English is extremely bad. Secondly, you're literally on a platform full of developers, and guess what ![Funny virus goes BRRR](https://private-user-images.githubusercontent.com/152000275/285578561-7bf4b17c-ca0c-4af5-9f02-085062d3d375.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NDU0NjQsIm5iZiI6MTcwMTc0NTE2NCwicGF0aCI6Ii8xNTIwMDAyNzUvMjg1NTc4NTYxLTdiZjRiMTdjLWNhMGMtNGFmNS05ZjAyLTA4NTA2MmQzZDM3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQwMjU5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTAxZDkxOWE3ZmQ0NjJkMjliNjE0ZjJiNTUxOGZhMTk1MTc4ZmRkNWE4ZDAxNzIxZWY5YjRiYjQ4Yjk4MDA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4p1vgZ9ACtf3R7-pc0tP3Ii_EXNQrT-0DZbqL_5MUq8)
> > # No one will fall for that scam bud,
> > We dont want your shitty trojan, i litteraly made a github account (once again since i've got locked down) just to fucking reply to your stupid virus
> > **ps: you suck**
> 
> hi, can u provide me with the file hash?

Yep, and BTW they edited the issue to provide the real exe file and make them look like we're wrong, shame on him.
Heres the hash 

a5e0957c6fa77de73a7955c32a2154da7a7026fa52afa4d7b20ec06c78753a02
UltimMC Setup (Make By KOD).exe

![image](https://github.com/UltimMC/Launcher/assets/152000275/abcb2e4b-3290-49b4-bc12-9c7ae0fa5de1)
and plus, the file literally needed admin permission on startup (not normal for a install program)
![image](https://github.com/UltimMC/Launcher/assets/152000275/4129af67-0ba0-47d2-9520-1ec105704e2e)

**Comment by create-juicey-app** [comment]
Back with my main acc, it's a shame that people like them exist, trying to install viruses, miners, keyloggers..
Like 70% of all computers already antivirus installed on them

So that guy's technique won't work, unless you're dumb enough to install some program from a random dude that requires admin rights on startup.

# SHAME ON YOU

**Comment by create-juicey-app** [comment]
You know what I'm gonna test that on a sandbox. 
Edit : also found out that this guy's account is probably a bot, look at it's starred projects
Not sure tho

**Comment by KienPC1234** [comment]
# I had no intention of putting a Trojan in this file, sorry because I used bad installer creation software
# https://www.youtube.com/watch?v=UyXwVEuMXm0

**Comment by KienPC1234** [comment]
> Bạn biết tôi sẽ kiểm tra điều đó trên hộp cát rồi đấy. Chỉnh sửa: cũng phát hiện ra rằng tài khoản của anh chàng này có thể là bot, hãy nhìn vào các dự án được gắn dấu sao Không chắc chắn lắm

I'm Not a Bot

**Comment by create-juicey-app** [comment]
Yep, I executed the code in a software that permits me to see what's the program doing, it is in fact a setup executable but really outdated, so dated in fact that most antiviruses thinks it's dangerous, I've checked that file test seem to not dangerous I'm gonna still do advanced research but for the moment ***you're forgiven*** but don't post links like that without tell what the program actually does + Don't use setup things, upload zip files, way better, or even. compile, or make a executable zip. Byee

Edit : @KienPC1234 you're forgiven

**Comment by Neptune650** [comment]
I've made the Actions scheduled every month so that the download link won't expire, please refrain from downloading this kind of software from dubious sources for your own safety.
