### ISSUE TITLE
For anyone having trouble downloading UltiMC (Pointed out by Labnann)

### ISSUE THREAD

**Issue by piratedlemon** [UltimMC/Launcher#320]
Workaround: Try getting your artifact from GitHub actions.

The current build can be availed here:
https://github.com/UltimMC/Launcher/actions/runs/6843330274

Check under the artifacts section. :)

Edit: 
Download it from there (it requires an account to access iirc)
Don't trust any outside sources apart from the official ultimc,

_Originally posted by @Labnann in https://github.com/UltimMC/Launcher/issues/316#issuecomment-1811869437_

**Comment by adilsary1** [comment]
How do i download it? Can't find any button for it
