### ISSUE TITLE
My Instance Does Not Have A LWJGL

### ISSUE THREAD

**Issue by Sardine-G** [UltimMC/Launcher#321]
### Operating System

Linux

### Description of bug

In my intances of minecraft (1.20.2) it does not have a LWJGL On the version menu
and i need lwjgl to use vulkan mod
![Snapshot_2023-12-02_12-03-37](https://github.com/UltimMC/Launcher/assets/152669598/fa047d36-d02a-4c48-88d8-47d6753b5180)

### Steps to reproduce

well just open launcher
edit Instance
version and there is no LWJGL

### Suspected cause

Instance or maybe the launcher

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
Unable to reproduce.
