### ISSUE TITLE
Code error: 0x1

### ISSUE THREAD

**Issue by Pelmen228ProMax** [UltimMC/Launcher#326]
UltimMC version: 0.7.0-custom

Launched instance in online mode

authserver.mojang.com resolves to:
    [143.204.215.70, 143.204.215.42, 143.204.215.57, 143.204.215.76]

session.minecraft.net resolves to:
    [13.107.246.44, 13.107.213.44]

textures.minecraft.net resolves to:
    [13.107.213.44, 13.107.246.44]

api.mojang.com resolves to:
    [13.107.213.44, 13.107.246.44]

Minecraft folder is:
G:/GAMES/UltimMC/instances/1.16.4/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 1.8.0_391, using 32-bit architecture, from Oracle Corporation.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.minecraft.client.main.Main

Native path:
  G:/GAMES/UltimMC/instances/1.16.4/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  G:/GAMES/UltimMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  G:/GAMES/UltimMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  G:/GAMES/UltimMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  G:/GAMES/UltimMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  G:/GAMES/UltimMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  G:/GAMES/UltimMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  G:/GAMES/UltimMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  G:/GAMES/UltimMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  G:/GAMES/UltimMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  G:/GAMES/UltimMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  G:/GAMES/UltimMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  G:/GAMES/UltimMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  G:/GAMES/UltimMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  G:/GAMES/UltimMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  G:/GAMES/UltimMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  G:/GAMES/UltimMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  G:/GAMES/UltimMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  G:/GAMES/UltimMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  G:/GAMES/UltimMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  G:/GAMES/UltimMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  G:/GAMES/UltimMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  G:/GAMES/UltimMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  G:/GAMES/UltimMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  G:/GAMES/UltimMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  G:/GAMES/UltimMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  G:/GAMES/UltimMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  G:/GAMES/UltimMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  G:/GAMES/UltimMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  G:/GAMES/UltimMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  G:/GAMES/UltimMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  G:/GAMES/UltimMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  G:/GAMES/UltimMC/libraries/com/mojang/minecraft/1.16.4/minecraft-1.16.4-client.jar

Native libraries:
  G:/GAMES/UltimMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  G:/GAMES/UltimMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  G:/GAMES/UltimMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  G:/GAMES/UltimMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  G:/GAMES/UltimMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  G:/GAMES/UltimMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  G:/GAMES/UltimMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  G:/GAMES/UltimMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username <ACCESS TOKEN> --version 1.16.4 --gameDir G:/GAMES/UltimMC/instances/1.16.4/.minecraft --assetsDir G:/GAMES/UltimMC/assets --assetIndex 1.16 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType Local --versionType release

Window size: 854 x 480

Java Arguments:
[-javaagent:G:/GAMES/UltimMC/injectors/authlib-injector-1.2.4.jar=http://localhost:57601, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1664m, -Duser.language=en]

Minecraft process ID: 6168

Error occurred during initialization of VM
Could not reserve enough space for 1703936KB object heap
The process exited with code 1 (0x1).
Please note that sometimes neither the exit code nor its description is enough to diagnose problems!
Always download the entire report, not just the exit code.

**Comment by Neptune650** [comment]
You're running out of memory, not related to UltimMC.
