### ISSUE TITLE
Unable to launch any Minecraft version with no errors or exitcode in the console.

### ISSUE THREAD

**Issue by pohod** [UltimMC/Launcher#327]
### Operating System

Windows

### Description of bug

I have used this launcher for a while on my other PC. But when i tried to use it on my laptop I was unable to start any version of Minecraft without any feedback in the console. I have tested it and it failed on Minecraft <=1.0, 1.16.* and 1.20.*.
Log for Minecraft 1.0:
```
UltimMC version: 0.7.0-custom


Launched instance in online mode

authserver.mojang.com resolves to:
    [18.244.146.37, 18.244.146.76, 18.244.146.71, 18.244.146.10]

session.minecraft.net resolves to:
    [13.107.246.44, 13.107.213.44]

textures.minecraft.net resolves to:
    [13.107.246.44, 13.107.213.44]

api.mojang.com resolves to:
    [13.107.246.44, 13.107.213.44]


Minecraft folder is:
C:/gm/UltimMC/instances/1.0/.minecraft


Java path is:
C:/Program Files/Java/jdk-17/bin/javaw.exe


Checking Java version...
Java is version 17.0.8, using 64-bit architecture, from Oracle Corporation.


Main Class:
  

Native path:
  C:/gm/UltimMC/instances/1.0/natives

Traits:
traits legacyLaunch
traits texturepacks

Libraries:
  C:/gm/UltimMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/gm/UltimMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/gm/UltimMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/gm/UltimMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/gm/UltimMC/libraries/com/mojang/minecraft/1.0/minecraft-1.0-client.jar

Native libraries:
  C:/gm/UltimMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/gm/UltimMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Params:
  

Window size: 854 x 480


```
Looking at the log I can see some odd details like the main class and params fields not being specified in the log:
```
Main Class:
  
```
```
Params:
  
```
The log also seemingly provided no exitcode or error message and just abruptly ends (yes it wasn't me to paste the full log in).
This might be one of the harder to reproduce/unique to device issues, if that's so, can anybody suggest a fix for this issue?

### Steps to reproduce

For me, with Microsoft Windows 7 x64, Java 17, UltimMC version 0.7.0-custom:
* Create a vanilla Minecraft instance of any version.
* Launch it.

### Suspected cause

Possibly a fail to figure out/store launch parameters like the main MC class and start params.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
This is really odd, I'm unable to reproduce it, does the error still occur?
