### ISSUE TITLE
cant upload any skin

### ISSUE THREAD

**Issue by idk422** [UltimMC/Launcher#331]
### Description of bug

i downloaded like 8 skins but ultimmc did not accept any

### Steps to reproduce

idk

### Suspected cause

idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Luuls** [comment]
me too

### Operating system
Ubuntu 22.04

**Comment by Neptune650** [comment]
Fixed (by disabling the buttons, since ely.by doesn't provide an API to change skins, just use their web UI)
