### ISSUE TITLE
Ely.by skins not working

### ISSUE THREAD

**Issue by tomadamadeira2** [UltimMC/Launcher#332]
### Description of bug

I tried putting the username instead of the email and still didn't worked, is there any Permanent fix which isn't some weird shit i don't understand?

### Steps to reproduce

Idk honestly, i logged my ely.by account by putting the username instead but the skins are not working

### Suspected cause

Huh.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheDelicio** [comment]
Did you solve the issue? i have the same issue here

**Comment by ErikShel17** [comment]
From the last issue that is already closed I saw that ely by skin system is currently work in progress still. However me and my friend managed to get ely by skins to work in our private server by installing some plugin that allows usage of ely by skin system.

**Comment by Neptune650** [comment]
![2024-03-11_21 15 23](https://github.com/UltimMC/Launcher/assets/62727185/61c7c6e8-e8d3-4ba3-8f9a-f1c455ff7b9f)
Fixed with latest commit.

**Comment by TheDelicio** [comment]
> From the last issue that is already closed I saw that ely by skin system is currently work in progress still. However me and my friend managed to get ely by skins to work in our private server by installing some plugin that allows usage of ely by skin system.

witch plugin and version, i would like to use this in my singleplayer world
