### ISSUE TITLE
No longer opening

### ISSUE THREAD

**Issue by ghost** [UltimMC/Launcher#335]
### Operating System

Windows

### Description of bug

I downloaded the "Windows (32-bit and 64-bit)". To update the program, but now the program does not open at all

### Steps to reproduce

1. Download from the downloads
2. Replace files from zip to folder
3. click on the exe
4. It does not open

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
So I reverted the changes by replacing the replaced parts with an backup and it seems to work again

**Comment by sunsushishine** [comment]
same problem

**Comment by ghost** [comment]
same thing, C0000005 error on the newest version but not on an older one

**Comment by Neptune650** [comment]
Try deleting accounts.json and see if the error still happens.

**Comment by willyanUBK** [comment]
> Try deleting accounts.json and see if the error this happens.

Doesn't work, sadly, I even tried to fresh install it and it doesn't open either.
It looks like it's something on the executable, I can update every file and it works, but if i change the .exe it doesn't open anymore

**Comment by MrWeez** [comment]
Same

**Comment by PXNDA-E36** [comment]
Same issue here. Downloaded it and cannot open the .exe file.

**Comment by ErikShel17** [comment]
This new version doesn't work for me either. I even thought the issue is with my Java so I reinstalled it, but turns out it's not.

**Comment by Nyaa888** [comment]
Fresh Install and no sign of .exe opening. does anyone have the old version?

**Comment by ESHARK22** [comment]
Old builds can be downloaded from https://github.com/UltimMC/Launcher/actions?query=is%3Asuccess

eg [this build](https://github.com/UltimMC/Launcher/actions/runs/8178810390) seems to work

**Comment by Neptune650** [comment]
> Old builds can be downloaded from https://github.com/UltimMC/Launcher/actions?query=is%3Asuccess
> 
> eg [this build](https://github.com/UltimMC/Launcher/actions/runs/8178810390) seems to work

Does [this](https://github.com/UltimMC/Launcher/actions/runs/8196663858) one work?

**Comment by ghost** [comment]
yep, tested it and works

**Comment by krymzone** [comment]
Same problem

**Comment by Neptune650** [comment]
> yep, tested it and works

How about [this](https://github.com/UltimMC/Launcher/actions/runs/8199011777) one?

Sorry if this can be annoying, it just happens I don't have a Windows device to test and this is the best way I figured to find out which version broke it.

**Comment by ghost** [comment]
works too

**Comment by Neptune650** [comment]
> works too

[This](https://github.com/UltimMC/Launcher/actions/runs/8209259167) one?

**Comment by Shallow-Sleet** [comment]
just wanted to comment to get notifs on this issue :yaoming:

**Comment by willyanUBK** [comment]
> > works too
> 
> [This](https://github.com/UltimMC/Launcher/actions/runs/8209259167) one?

Not working for me, [#367](https://github.com/UltimMC/Launcher/actions/runs/8199011777) was the last one that worked apparently

**Comment by ghost** [comment]
same here, but 367 crashes upon exit

**Comment by willyanUBK** [comment]
Hmm, 367 does open and closes normally for me, but my ely.by account got removed and now I can't connect it again, it gives me a "Minecraft Java profile acquisition failed." error, idk if it's a temporary error or not

**Comment by ghost** [comment]
> Hmm, 367 does open and closes normally for me, but my ely.by account got removed and now I can't connect it again, it gives me a "Minecraft Java profile acquisition failed." error, idk if it's a temporary error or not

this was supposed to be fixed by build [#370](https://github.com/UltimMC/Launcher/actions/runs/8209928101) which doesn't work

**Comment by Neptune650** [comment]
Hopefully [this](https://github.com/UltimMC/Launcher/actions/runs/8240575335) should fix it, please try it.

**Comment by ErikShel17** [comment]
> Hopefully [this](https://github.com/UltimMC/Launcher/actions/runs/8240575335) should fix it, please try it.

Works for me!

**Comment by Neptune650** [comment]
Alright, that's good to hear, if anyone else faces this issue still, please reopen.

**Comment by willyanUBK** [comment]
> Hopefully [this](https://github.com/UltimMC/Launcher/actions/runs/8240575335) should fix it, please try it.

It worked for me too, It opens now and I can log in with my ely.by account, and even the new versions like 1.20.2 and upper works fine now, even the newest snapshot.
The only thing that still is not working, at least for me, are the ely.by skins, they don't load, neither the avatar or in-game

**Comment by Neptune650** [comment]
> It worked for me too, It opens now and I can log in with my ely.by account, and even the new versions like 1.20.2 and upper works fine now, even the newest snapshot. The only thing that still is not working, at least for me, are the ely.by skins, they don't load, neither the avatar or in-game

Glad to hear it works, as for the skin system, that's still a work in progress for now.
