### ISSUE TITLE
can't add skin

### ISSUE THREAD

**Issue by mohamedbaek** [UltimMC/Launcher#339]
### Description of bug

both of local and ely.by accounts can't upload skin the "upload skin" button is unable to click 
![Capture](https://github.com/UltimMC/Launcher/assets/163693204/3e350d7b-43cc-461d-96dc-1048ff8d8745)

### Steps to reproduce

idk what to put here

### Suspected cause

in past i installed ultimmc and has mojang account and both of local and ely.by was able to upload skin but i uninstalled it and in some weeks i installed it again by searching for this website but the file i installeed wasn't have mojang accont and this upload skin issue
![Capture](https://github.com/UltimMC/Launcher/assets/163693204/fe399d34-6a74-42c2-b9de-eeab82d44276)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by mohamedbaek** [comment]
operating system: windows 7

**Comment by Neptune650** [comment]
This is intentional, use the ely.by website to change your elyby skin.

**Comment by sebastianbhahn** [comment]
> This is intentional,

>because I want to phish private information from users

**Comment by Neptune650** [comment]
> > This is intentional,
> 
> > because I want to phish private information from users

You're free to browse [every single change](https://github.com/MultiMC/Launcher/compare/develop...UltimMC:Launcher:develop) we've made to the original MultiMC codebase, the reason why we keep this fork very simple, to keep it auditable.

**Comment by sebastianbhahn** [comment]
I'm referring to the demand that users enter their email and a password to "create an account" with some unknown website in order to be able to use their personal skin with an offline account.

**Comment by Neptune650** [comment]
> I'm referring to the demand that users enter their email and a password to "create an account" with some unknown website in order to be able to use their personal skin with an offline account.

We don't have any connection to ely.by and you can actually just use whatever credentials you want to make an account... or simply use an entirely offline account.

**Comment by sebastianbhahn** [comment]
An entirely offline account generates a random skin, which cannot be changed.

**Comment by sebastianbhahn** [comment]
which is clearly intentional behavior.
