### ISSUE TITLE
Version 1.20.2 fails to start of M1 mac

### ISSUE THREAD

**Issue by AlphaZero4000** [UltimMC/Launcher#340]
### Operating System

macOS

### Description of bug

UltimMC version: 0.7.0-custom

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.40, 13.107.213.40]

textures.minecraft.net resolves to:
    [13.107.213.40, 13.107.246.40]

api.mojang.com resolves to:
    [13.107.246.40, 13.107.213.40]

Minecraft folder is:
/Users/ilove/Documents/UltimMC.app/Data/instances/1.20.4/.minecraft

Java path is:
/usr/bin/java

Checking Java version...
Java is version 21.0.2, using 32-bit architecture, from Eclipse Adoptium.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.minecraft.client.main.Main

Native path:
  /Users/ilove/Documents/UltimMC.app/Data/instances/1.20.4/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /Users/ilove/Documents/UltimMC.app/Data/libraries/ca/weblite/java-objc-bridge/1.1/java-objc-bridge-1.1.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/com/mojang/authlib/6.0.52/authlib-6.0.52.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/commons-io/commons-io/2.13.0/commons-io-2.13.0.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/net/java/dev/jna/jna-platform/5.13.0/jna-platform-5.13.0.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar
  /Users/ilove/Documents/UltimMC.app/Data/libraries/com/mojang/minecraft/1.20.4/minecraft-1.20.4-client.jar

Native libraries:

Params:
  --username  --version 1.20.4 --gameDir /Users/ilove/Documents/UltimMC.app/Data/instances/1.20.4/.minecraft --assetsDir /Users/ilove/Documents/UltimMC.app/Data/assets --assetIndex 12 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-javaagent:/Users/ilove/Documents/UltimMC.app/Data/injectors/authlib-injector-1.2.5.jar=http://localhost:51281, -Dauthlibinjector.noShowServerName, -Xdock:icon=icon.png, -Xdock:name="UltimMC: 1.20.4", -XstartOnFirstThread, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 21275

[authlib-injector] [INFO] Logging file: /Users/ilove/Documents/UltimMC.app/Data/instances/1.20.4/.minecraft/authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.5
[authlib-injector] [INFO] Authentication server: http://localhost:51281
[authlib-injector] [WARNING] You are using HTTP protocol, which is INSECURE! Please switch to HTTPS if possible.
Using onesix launcher.

[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.properties.Property] with [Yggdrasil Public Key Transformer]
Failed to start Minecraft:
Exiting with -1
java.lang.IllegalArgumentException: Invalid UUID string: 
	at java.base/java.util.UUID.fromString1(UUID.java:282)
	at java.base/java.util.UUID.fromString(UUID.java:260)
	at com.mojang.util.UndashedUuid.fromStringLenient(UndashedUuid.java:14)
	at net.minecraft.client.main.Main.main(SourceFile:151)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Process exited with code 255 (0xff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### Steps to reproduce

Create an instance of 1.20.4 without installing anything. 
Run the instance. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
Can you try recreating the local profile?

**Comment by AlphaZero4000** [comment]
I just tried that and the same issue occurs.

**Comment by WalkingPizza** [comment]
Try installing a `x86-64` version of Java, that's what fixed it for me.

**Comment by Neptune650** [comment]
Alright now that I notice that yes, install a x86-64 Java.

**Comment by AriesAlex** [comment]
updating launcher helped for me
