### ISSUE TITLE
Skin options for accounts in the account management tab are greyed out/unclickable.

### ISSUE THREAD

**Issue by daniidsiilva** [UltimMC/Launcher#344]
### Operating System

Windows 10

### Description of bug

Skin options for accounts in the account management tab are greyed out/unclickable.
![M8738696](https://github.com/UltimMC/Launcher/assets/141585237/58760862-ade7-416f-87ea-b503b27fa751)

### Steps to reproduce

1. Download and install UltiMC.
2. Create an account.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
This is intentional.

**Comment by HWdriver** [comment]
> This is intentional.

why
