### ISSUE TITLE
UltimMC.app cannot be opened because of a problem.

### ISSUE THREAD

**Issue by thatdolphinguy** [UltimMC/Launcher#345]
### Operating System

macOS

### Description of bug

I tried to open UltimMC.app, and instead of it launching, I got an error instead.
`Process:               UltimMC [1241]
Path:                  /Users/USER/Downloads/UltimMC.app/Contents/MacOS/UltimMC
Identifier:            org.multimc.UltimMC
Version:               0.7.0.-1 (0.7.0.-1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           UltimMC [1241]
User ID:               501

Date/Time:             2024-04-07 14:48:31.057 -0400
OS Version:            macOS 11.7.10 (20G1427)
Report Version:        12
Anonymous UUID:        223483B1-C63E-0824-6C10-DE5DF85AF473

Time Awake Since Boot: 700 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 02B0BFE0-0F55-3C6E-ADEF-7DD25145A881
Library not loaded: @executable_path/../MacOS/libgthread-2.0.0.dylib
  Referenced from: /Users/****/Downloads/UltimMC.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
  Reason: image not found

Binary Images:
       0x10ff3b000 -        0x1103eefff +org.multimc.UltimMC (0.7.0.-1 - 0.7.0.-1) <9D744006-0D4E-3EB5-AF4F-95B9754F8014> /Users/USER/Downloads/UltimMC.app/Contents/MacOS/UltimMC
       0x11058f000 -        0x1105b2fff +libLauncher_quazip.dylib (0) <034C1B94-171E-38FE-B910-4AE22E5D3257> /Users/USER/Downloads/UltimMC.app/Contents/MacOS/libLauncher_quazip.dylib
       0x1105ca000 -        0x1105ddfff +libLauncher_nbt++.dylib (0) <11C855B8-A1AA-3B73-A770-2BD12BBEA43C> /Users/USER/Downloads/UltimMC.app/Contents/MacOS/libLauncher_nbt++.dylib
       0x1105f9000 -        0x110630fff +QtXml (0) <6AD9FBA9-91B8-37D9-B7B5-CB982898B2C5> /Users/USER/Downloads/UltimMC.app/Contents/Frameworks/QtXml.framework/Versions/5/QtXml
       0x110644000 -        0x110647fff +QtConcurrent (0) <797A9375-C2D0-35FD-9B78-38CF406572CC> /Users/USER/Downloads/UltimMC.app/Contents/Frameworks/QtConcurrent.framework/Versions/5/QtConcurrent
       0x110654000 -        0x110663fff +libLauncher_iconfix.dylib (0) <BA3C1454-6BA2-3BE6-9E4E-52B41F9E4878> /Users/USER/Downloads/UltimMC.app/Contents/MacOS/libLauncher_iconfix.dylib
       0x110675000 -        0x110abcfff +QtWidgets (0) <53C15E9F-220A-37F1-B3D5-6D12D61A9C39> /Users/USER/Downloads/UltimMC.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x110c28000 -        0x110c2bfff +libLauncher_rainbow.dylib (0) <DBCB3E76-9C39-381F-920A-A6471365E58F> /Users/USER/Downloads/UltimMC.app/Contents/MacOS/libLauncher_rainbow.dylib
       0x110c3a000 -        0x110d45fff +QtNetwork (0) <10B405BD-7D07-3420-BF12-F7F58C84E3A8> /Users/USER/Downloads/UltimMC.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x110d94000 -        0x11125bfff +QtGui (0) <03419059-5C1F-3574-9843-5F1D08FDF2FA> /Users/USER/Downloads/UltimMC.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x111378000 -        0x11181ffff +QtCore (0) <B447BD4D-72C5-30A1-ACA6-288861C4C366> /Users/USER/Downloads/UltimMC.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x1118ed000 -        0x111966fff +libpcre2-16.0.dylib (0) <21D962E3-9052-3CE8-A648-B4C69EFCB9C6> /usr/local/Cellar/pcre2/10.42/lib/libpcre2-16.0.dylib
       0x11196f000 -        0x111a25fff +libzstd.1.5.5.dylib (0) <AC1A60CE-C8C3-35A3-9342-1F59B5F6737D> /usr/local/Cellar/zstd/1.5.5/lib/libzstd.1.5.5.dylib
       0x116617000 -        0x1166b2fff  dyld (852.2) <BD607394-9008-33B9-B98B-A5886668E52C> /usr/lib/dyld
    0x7fff2029b000 -     0x7fff202f0fff  libc++.1.dylib (905.6) <5BA6B5ED-7842-3B13-86B0-00EB511CE2FE> /usr/lib/libc++.1.dylib
    0x7fff203b5000 -     0x7fff20852fff  com.apple.CoreFoundation (6.9 - 1778.105) <BDBC7E56-C3AC-3561-A7C6-A422093307AD> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff21090000 -     0x7fff213eefff  com.apple.Foundation (6.9 - 1778.105) <4F4709DD-C198-3AA1-86A0-71D2F2FDD65D> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff220f8000 -     0x7fff2244ffff  com.apple.security (7.0 - 59754.141.1.702.3) <5A52B8E8-B1AF-3F29-AC97-5DBEE8C6A6AC> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff22a20000 -     0x7fff22acefff  com.apple.framework.IOKit (2.0.2 - 1845.120.6) <A395F442-1253-3CA9-953F-7A235EEB7F67> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff22b29000 -     0x7fff23874fff  com.apple.AppKit (6.9 - 2022.70.111) <FA68A033-FD64-3F0B-8869-5C42CB9C6BE4> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff26495000 -     0x7fff2649bfff  com.apple.DiskArbitration (2.7 - 2.7) <21325211-A5F7-3AB9-BDFE-6B6DC06E587E> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff2a5c6000 -     0x7fff2a5d8fff  libz.1.dylib (76.140.1) <A2FF8D14-1632-3047-9829-CC90239F97FF> /usr/lib/libz.1.dylib
    0x7fff2a692000 -     0x7fff2a693fff  libSystem.B.dylib (1292.120.1) <A8E7368E-58FA-31E5-8D4D-FC2FED6100E6> /usr/lib/libSystem.B.dylib
    0x7fff30189000 -     0x7fff30189fff  com.apple.CoreServices (1122.45 - 1122.45) <05DA2462-9BFC-38D9-820A-8842710471D6> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff33378000 -     0x7fff33378fff  com.apple.ApplicationServices (48 - 50) <59E17F70-AB03-320D-B955-8F87F2C40898> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices

Model: MacBookPro8,1, BootROM MBP81.0047.B2A, 2 processors, Dual-Core Intel Core i5, 2.4 GHz, 8 GB, SMC 1.68f99
Graphics: kHW_IntelHD3000Item, Intel HD Graphics 3000, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80CE, 0x4D34373142353237334348302D4348392020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80CE, 0x4D34373142353237334348302D4348392020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xD6), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1680.11)
Bluetooth: Version 8.0.5d7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: OCZ-VERTEX4, 512.11 GB
Serial ATA Device: MATSHITADVD-R   UJ-8A8
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: USB Optical Mouse
USB Device: IR Receiver
USB Device: USB 2.0 Bus
USB Device: FaceTime HD Camera (Built-in)
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 25.1`

### Steps to reproduce

Open UltimMC.app

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jpdagostin0** [comment]
Install qt5. Either use [brew.sh](https://formulae.brew.sh/formula/qt@5) or [MacPorts](https://ports.macports.org/port/qt5/). I used brew.
In terminal: `% brew install qt@5` OR `% sudo port install qt5`

Possibly related fix for: #329 #258 #234

Tested working on macOS 14.4.1, Intel

**Comment by thatdolphinguy** [comment]
> Install qt5. Either use [brew.sh](https://formulae.brew.sh/formula/qt@5) or [MacPorts](https://ports.macports.org/port/qt5/). I used brew. In terminal: `% brew install qt@5` OR `% sudo port install qt5`
> 
> Possibly related fix for: #329 #258 #234
> 
> Tested working on macOS 14.4.1, Intel

Exact same thing happens.

**Comment by thatdolphinguy** [comment]
Computer is long gone. Can’t test anything now so I’m just going to close this.
