### ISSUE TITLE
I cant login to my account Ely.by

### ISSUE THREAD

**Issue by IgorVasilekIV** [UltimMC/Launcher#348]
### Operating System

Windows

### Description of bug

I can't log in to my account Ely.by and it wrote to me: "Аунтефикация пользователя Mojang не удалась из-за проблем с сетью. (Mojang's authentication failed due to network issues.)" I'm in Russia and tried using a VPN, but it didn't work either.
![Снимок экрана (754)1](https://github.com/UltimMC/Launcher/assets/62138809/835ebe24-c538-4127-8f68-389c93bc53a1)

### Steps to reproduce

Just try to add your account Ely.by

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by IgorVasilekIV** [comment]
I used a translator, so if anything is wrong, please correct me.

**Comment by ValentinStars** [comment]
I have exactly the same

**Comment by Phelphy** [comment]
Same here.

**Comment by Phelphy** [comment]
I doubt this'll be fixed to be honest.

**Comment by R0DAT** [comment]
You most likely used the wrong login details. I had the same problem, but turns out i had the wrong password.

**Comment by lemyqross** [comment]
https://github.com/UltimMC/Launcher/issues/342#issuecomment-2031358445

**Comment by IgorVasilekIV** [comment]
> [#342 (comment)](https://github.com/UltimMC/Launcher/issues/342#issuecomment-2031358445)

It would be nice if it worked, but it doesn't😫

**Comment by IgorVasilekIV** [comment]
> You most likely used the wrong login details. I had the same problem, but turns out i had the wrong password.

Didn't work either
I even changed my password to a different one

**Comment by IgorVasilekIV** [comment]
Or maybe it's possible to add an account via accounts.json file?

**Comment by medved1231** [comment]
yesssss!! Write nicname and pasvord LOL GOOD LUCK)))))

**Comment by IgorVasilekIV** [comment]
> yesssss!! Write nicname and pasvord LOL GOOD LUCK)))))

I need instructions😭😭
Но если это рофл -_-

**Comment by medved1231** [comment]
просто откриваи акаунт ели би и пиши ник а внизу парол .. I don't know Russian well

**Comment by ValentinStars** [comment]
Вижу ты совсем глупый.. Медведь1231
Сам то не правильно переводчик написал так ещё и обманываешь. 
И ещё что ты тут написал, в этом и есть ошибка гений. Но если ты запритворялся прям хорошо то на.
I see you are completely stupid.. Medved1231
The translator himself wrote it incorrectly and you are also deceiving.
And what else you wrote here, this is the mistake of genius. But if you pretended to be really good, then no.

**Comment by medved1231** [comment]
wtf man ??я просто дал совет катори работал на мои лаунчере 
![саot_4](https://github.com/UltimMC/Launcher/assets/169712906/c93065f9-2a19-47b5-8214-fc174e20e903)
вот посмотри сам я просто писал ник на ели би и парол

**Comment by medved1231** [comment]
я не хочу не каму обмануть и смист тоже нету . я просто сказал спосаб катори работал . ишо можеш попробавать с впн-ом
bye bye

**Comment by medved1231** [comment]
ValentinStars НУ ЧТО работал????

**Comment by IgorVasilekIV** [comment]
> wtf man ??я просто дал совет катори работал на мои лаунчере ![саot_4](https://private-user-images.githubusercontent.com/169712906/333140579-c93065f9-2a19-47b5-8214-fc174e20e903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDMxNDUsIm5iZiI6MTcxNjcwMjg0NSwicGF0aCI6Ii8xNjk3MTI5MDYvMzMzMTQwNTc5LWM5MzA2NWY5LTJhMTktNDdiNS04MjE0LWZjMTc0ZTIwZTkwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwNTU0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2MzYmM0ZTllMTgyZTg5ZGRhYjU3MDhiODMwZTM0OWVkMTYyNjFjMTg0ZWZhY2I1ZWRjMDQxODU0NThmNzY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uS7zcP4DDJkkmM7aTxvtkxPdUGeGdYICNHhmdF48gmw) вот посмотри сам я просто писал ник на ели би и парол

Пздц у тебя даже в лаунчере руский язык, ты ебобо?

**Comment by medved1231** [comment]
> > wtf man ??я просто дал совет катори работал на мои лаунчере ![саot_4](https://private-user-images.githubusercontent.com/169712906/333140579-c93065f9-2a19-47b5-8214-fc174e20e903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDMxNDUsIm5iZiI6MTcxNjcwMjg0NSwicGF0aCI6Ii8xNjk3MTI5MDYvMzMzMTQwNTc5LWM5MzA2NWY5LTJhMTktNDdiNS04MjE0LWZjMTc0ZTIwZTkwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwNTU0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2MzYmM0ZTllMTgyZTg5ZGRhYjU3MDhiODMwZTM0OWVkMTYyNjFjMTg0ZWZhY2I1ZWRjMDQxODU0NThmNzY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uS7zcP4DDJkkmM7aTxvtkxPdUGeGdYICNHhmdF48gmw) вот посмотри сам я просто писал ник на ели би и парол
> 
> Пздц у тебя даже в лаунчере руский язык, ты ебобо?

да у меня есть у вас нету чтоли?

**Comment by IgorVasilekIV** [comment]
> > > wtf man ??я просто дал совет катори работал на мои лаунчере ![саot_4](https://private-user-images.githubusercontent.com/169712906/333140579-c93065f9-2a19-47b5-8214-fc174e20e903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDMxNDUsIm5iZiI6MTcxNjcwMjg0NSwicGF0aCI6Ii8xNjk3MTI5MDYvMzMzMTQwNTc5LWM5MzA2NWY5LTJhMTktNDdiNS04MjE0LWZjMTc0ZTIwZTkwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwNTU0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2MzYmM0ZTllMTgyZTg5ZGRhYjU3MDhiODMwZTM0OWVkMTYyNjFjMTg0ZWZhY2I1ZWRjMDQxODU0NThmNzY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uS7zcP4DDJkkmM7aTxvtkxPdUGeGdYICNHhmdF48gmw) вот посмотри сам я просто писал ник на ели би и парол
> > 
> > 
> > Пздц у тебя даже в лаунчере руский язык, ты ебобо?
> 
> да у меня есть у вас нету чтоли?

блять.......

**Comment by IgorVasilekIV** [comment]
> > > > wtf man ??я просто дал совет катори работал на мои лаунчере ![саot_4](https://private-user-images.githubusercontent.com/169712906/333140579-c93065f9-2a19-47b5-8214-fc174e20e903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDMxNDUsIm5iZiI6MTcxNjcwMjg0NSwicGF0aCI6Ii8xNjk3MTI5MDYvMzMzMTQwNTc5LWM5MzA2NWY5LTJhMTktNDdiNS04MjE0LWZjMTc0ZTIwZTkwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwNTU0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2MzYmM0ZTllMTgyZTg5ZGRhYjU3MDhiODMwZTM0OWVkMTYyNjFjMTg0ZWZhY2I1ZWRjMDQxODU0NThmNzY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uS7zcP4DDJkkmM7aTxvtkxPdUGeGdYICNHhmdF48gmw) вот посмотри сам я просто писал ник на ели би и парол
> > > 
> > > 
> > > Пздц у тебя даже в лаунчере руский язык, ты ебобо?
> > 
> > 
> > да у меня есть у вас нету чтоли?
> 
> блять.......

А говорил что англичанин🤓

**Comment by Red0leader228** [comment]
> Вы, скорее всего, использовали неправильные данные для входа. У меня была та же проблема, но оказалось, что у меня был неправильный пароль.

I entered everything correctly, and like this товарищ, nothing works or helps, I can’t even play Minecraft offline

**Comment by IgorVasilekIV** [comment]
There is an error in the program, you need to enter not the email but the nickname that is indicated there -_-
