### ISSUE TITLE
phishing isn't acceptible.

### ISSUE THREAD

**Issue by sebastianbhahn** [UltimMC/Launcher#361]
### Role

"ely.by" phishing isn't acceptible.

### Suggestion

 publish the directory used to store local account skins

### Benefit

so you won't look like a scammer

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by regularuser548** [comment]
What do you mean? What phishing?

**Comment by Neptune650** [comment]
We don't run ely.by, ask them for this.

**Comment by sebastianbhahn** [comment]
That doesn't explain why using your own skin is disabled unless you use ely.by.
It's clearly intended to direct users to that site.
Why have you intentionally prevented offline, local accounts from using their own skins, and forced some random skin instead?
