### ISSUE TITLE
"We don't run ely.by, ask them for this"

### ISSUE THREAD

**Issue by sebastianbhahn** [UltimMC/Launcher#363]
### Role

I don't like your randomly generated skins which you force on offline acocunts

### Suggestion

don't lie to me

### Benefit

the default steve skin would be better than someone else's skin

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

ely.by, since you claim to have no affiliation with them, did NOT implement the behavior of an offline (NOT ely.by) account, generating some random skin and NOT allowing for customization. You're telling me to ask the people involved in ely.by, which I have already expressed disinterest in anyway, to what? make a fork of your fork? one removing the feature you've added to create randomized skins, and re-enabling skin customization; or even just making the generated skin an editable, easily accessible local file in the program directory?

In your own words, you have no affiliation with ely.by.
so the issue of offline account skins is your responsibility, not theirs.

I wasn't even going to respond again, but your snide dishonesty triggered my autistic rage.

**Comment by Darthagnon** [comment]
What's this? Random skins with offline accounts? It should only be Steve or Alex, unless something else funky is going on. No internet connection should be made for skins with an offline account.

**Comment by sebastianbhahn** [comment]
I just tried it with a fresh instance, no mods or modloaders installed.
skin looks like this:
![this](https://github.com/UltimMC/Launcher/assets/24922317/1a26676c-5c72-4846-ac80-576f27bbe085)

**Comment by sebastianbhahn** [comment]
made another local offline account. again, no mods, no modloader, fresh instance.
skin looks like this:
![this2](https://github.com/UltimMC/Launcher/assets/24922317/5c01ab4f-bcad-4997-b52b-6c223e1a08de)

**Comment by sebastianbhahn** [comment]
come to think of it, that first one, with the bracelet, I've seen before. when loading up minecraft in a fabric modding environment to test a mod I made before building it (so loading into minecraft without an actual user account). I thought it was just some weird addition in the mdk added for a laugh and not implemented into the actual build.

Seeing it again here, this might be something on the back end that minecraft (microsoft) devs themselves did for some reason. loading into minecraft without an official account loads up one of these weird skins. maybe.

**Comment by Darthagnon** [comment]
What version of Minecraft? I would like to test further, but I play mainly 1.6, 1.7.10, 1.12.2 and 1.17

**Comment by sebastianbhahn** [comment]
1.20.6

**Comment by saberwoo** [comment]
this has nothing to do with the luncher it a minecraft thing 
i dont remember in chich version they added those skin but they are just default skins in the game

**Comment by Darthagnon** [comment]
> 1.20.6

A bunch of new skins were added to Minecraft in v1.19.3 - according to the wiki, you will be assigned one based off your UUID while online, or randomly while offline. https://minecraft.fandom.com/wiki/Player

See also: https://www.minecraft.net/en-us/article/introducing-new-default-skins

These new skins look shite, Microsoft is ruining Minecraft, and for me, personally, I'll stick to older versions.

Those two skins in the screenshots are "Efe" and "Kai" and are part of the new default selection of 9 skins included in Minecraft v1.19.3. 

**Not an UltimMC bug, a nuMinecraft anti-feature**

**Comment by sebastianbhahn** [comment]
"Not an UltimMC bug, a nuMinecraft anti-feature"

with that, I guess I'll close this issue.

I didn't know about any new skins.
I play the newer versions for the new game features.
I agree, the skins are bad. It's why I was so annoyed.

microsoft diversity hires demanding "representation" I guess.
I already thought that "alex" was an unnecessary addition.
