### ISSUE TITLE
cat button is showing dog instead of cat

### ISSUE THREAD

**Issue by kumsuyu** [UltimMC/Launcher#389]
### Operating System

Windows

### Description of bug

When I press the cat button on the top tab, it shows a dog in the background.how can i solve that

### Steps to reproduce

1.find **_THE_** cat button
2.press it
3.its show **dog** picture

### Suspected cause

its some probly a forgotten button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
not even true smh
